"""Writes puzzlemanda/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: puzzlemanda_data.py <out dir of puzzlemanda_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def jstr(v):
    s = json.dumps(v, separators=(',', ':'))
    assert '\\' not in s
    return s.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


hit = dict(sym=meta['hitSym'], disc=meta['hitDisc'], star=meta['hitStar'], body=meta['hitBody'])
tf = meta['titleField']
lines = [
    'package puzzlemanda;',
    '',
    '// generated by puzzlemanda_data.py from the original SWF (do not edit)',
    '',
    '// the shape of a button as a run-length mask: rows of [x0, x1[ runs, HIT_Z pixels per Flash pixel, pixel (0, 0) at',
    '// (ox, oy) in the coordinates of the clip that draws it',
    'typedef Mask = {ox:Float, oy:Float, rows:Array<Array<Array<Int>>>};',
    '',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '\tstatic var _hit:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// the shapes of a cell (Cell.hit): sym, the fruits (symbol frames 1..5, in the symbol); disc and star, a bonus',
    '\t// (symbol frames 6..8: sprite 43 and its stars, sprite 42); body, the snake (cell frames 60..65, in the cell)',
    '\tpublic static function hit():{sym:Array<Mask>, disc:Mask, star:Mask, body:Array<Mask>} {',
    '\t\tif (_hit == null)',
    '\t\t\t_hit = haxe.Json.parse(HIT);',
    '\t\treturn _hit;',
    '\t}',
    '',
    '\tpublic static inline var HIT_Z = %d;' % meta['hitZ'],
    '\t// matrices [a, b, c, d, tx, ty]: the symbol in the cell on each frame (null: not there), the bonus (sprite 43) in',
    '\t// the symbol, its three stars in it (their rotation is given by their frame script)',
    '\tpublic static var SYM_MAT:Array<Array<Float>> = [%s];' % ', '.join('null' if m is None else arr(m) for m in meta['symMat']),
    '\tpublic static var BONUS_MAT:Array<Float> = %s;' % arr(meta['bonusMat']),
    '\tpublic static var STAR_MATS:Array<Array<Float>> = %s;' % arr(meta['starMats']),
    '',
    '\t// title.field: "NIVEAU n" in Impact 12 px (glyph i + 1 of anim "glyph" for TITLE_CHARS.charAt(i), its advance),',
    '\t// pen at TITLE_X on the baseline TITLE_BASE (title coordinates)',
    '\tpublic static inline var TITLE_CHARS = "%s";' % tf['chars'],
    '\tpublic static var TITLE_ADV:Array<Float> = %s;' % arr(tf['adv']),
    '\tpublic static inline var TITLE_X = %r;' % float(tf['x']),
    '\tpublic static inline var TITLE_BASE = %r;' % float(tf['base']),
    '\tpublic static inline var TITLE_COLOR = 0x%06X;' % tf['color'],
    '',
    '\tstatic var CLIPS = "%s";' % jstr(clips),
    '\tstatic var HIT = "%s";' % jstr(hit),
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
