"""Writes kanjigaiden/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: kanjigaiden_data.py <out dir of kanjigaiden_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def jstr(v):
    s = json.dumps(v, separators=(',', ':'))
    assert '\\' not in s
    return s.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


bb = meta['bamboo']
lines = [
    'package kanjigaiden;',
    '',
    '// generated by kanjigaiden_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '\tstatic var _widths:Array<Array<Dynamic>> = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// mcMonkey._width at _xscale 100: [diff - 1][frame of smc - 1] -> the width, or the width for each frame of the',
    '\t// banana (smc.smc, 1..8)',
    '\tpublic static function monkeyWidths():Array<Array<Dynamic>> {',
    '\t\tif (_widths == null)',
    '\t\t\t_widths = haxe.Json.parse(WIDTHS);',
    '\t\treturn _widths;',
    '\t}',
    '',
    '\t// the score texts drawn (anim "scoreTxt", frame i + 1)',
    '\tpublic static var SCORES:Array<Int> = [%s];' % ', '.join(str(s) for s in meta['scores']),
    '\t// warning._width / _height on its first frame',
    '\tpublic static inline var WARN_W = %r;' % float(meta['warn'][0]),
    '\tpublic static inline var WARN_H = %r;' % float(meta['warn'][1]),
    '\t// children of the bamboo (matrices [a, b, c, d, tx, ty] in the bamboo): the outline masking the strip `mask`, the',
    '\t// dot, `bottom` and `taupe` (anims bbStalk<plan>, bbVine<plan>, bbDot<plan>, bbBottom<plan>, bbTaupe<plan>)',
    '\tpublic static var BB_STALK:Array<Float> = %s;' % arr(bb['stalk']),
    '\tpublic static var BB_VINE:Array<Float> = %s;' % arr(bb['vine']),
    '\tpublic static var BB_DOT:Array<Float> = %s;' % arr(bb['dot']),
    '\tpublic static var BB_BOTTOM:Array<Float> = %s;' % arr(bb['bottom']),
    '\tpublic static var BB_TAUPE:Array<Float> = %s;' % arr(bb['taupe']),
    '\tpublic static inline var BB_BOTTOMS = %d;' % bb['bottoms'],
    '\tpublic static inline var BB_TAUPES = %d;' % bb['taupes'],
    '',
    '\tstatic var CLIPS = "%s";' % jstr(clips),
    '\tstatic var WIDTHS = "%s";' % jstr(meta['monkeyWidth']),
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
