package klinkersurprise;

// generated by klinkersurprise_data.py from the original SWF (do not edit)
class Data {
	// mcInter: placement of the time bars b0 and b1 (x, y, xscale, yscale)
	public static var B0:Array<Float> = [199.8, 9.45, 1.0, 1.0];
	public static var B1:Array<Float> = [100.35, 9.45, -1.0, 1.0];
	// mcInter.field (Larabiefont 20, centred): characters of the anim glyph, their advances, text area x0..x1,
	// first baseline (Flash layout: 2 px gutter, baseline at the ascent)
	public static var FIELD_CHARS = "LEV'0123456789";
	public static var FIELD_ADV:Array<Float> = [10.5664, 10.5664, 10.5664, 10.5664, 10.5664, 10.5664, 10.5664, 10.5664, 10.5664, 10.5664, 10.5664, 10.5664, 10.5664, 10.5664];
	public static inline var FIELD_X0 = 88.15;
	public static inline var FIELD_X1 = 211.3;
	public static inline var FIELD_BASE = 15.9784;
	// mcLight pictures light0..: texture pixels per Flash pixel of the clip
	public static var LIGHT_RES:Array<Float> = [0.0625, 0.125, 0.25, 0.5];
}
