"""Writes hexile/Data.hx from the asset pipeline output (meta.json).
usage: hexile_data.py <out dir of hexile_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def num(x):
    return repr(float(x)) if isinstance(x, float) and not float(x).is_integer() else repr(int(x)) if float(x).is_integer() else repr(x)


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return num(v)


def digits(key):
    d = meta[key]
    return '{adv: %s, x0: %s, x1: %s, base: %s, align: "%s", anim: "%s", layers: %d}' % (
        arr([float(a) for a in d['adv']]), num(d['x0']), num(d['x1']), num(d['base']), d['align'], key, d['layers'])


def masks(key):
    return '[' + ', '.join('{x: %d, y: %d, rows: "%s"}' % (m['x'], m['y'], m['rows']) for m in meta['masks'][key]) + ']'


def layout(key):
    # per frame of the base (1 + number of soldiers): [kind, x, y, alpha] in depth order
    return '[\n' + ',\n'.join('\t\t' + arr(f) for f in meta['bases'][key]) + '\n\t]'


cb = meta['castleBase']
lines = [
    'package hexile;',
    '',
    '// generated by hexile_data.py from the original SWF (do not edit)',
    'class Data {',
    '\t// Socle.setType(Dirt): [height, base.smc frame] of the 2 variants (anim hexD: variant * 7 + texture)',
    '\tpublic static var DIRT:Array<Array<Int>> = %s;' % arr(meta['dirt']),
    '\t// Socle.setType(Mountain): heights from MOUNT_MIN (anim hexM: height - MOUNT_MIN + 1)',
    '\tpublic static inline var MOUNT_MIN = %d;' % meta['mountMin'],
    '\t// soldiers (kind 0) and their shadows (kind 1) placed by the base timelines, for each frame (1 + number of',
    '\t// soldiers): [kind, x, y, alpha] in depth order (sprites 61: Beach, 35: Dirt and the castle, 65: Mountain)',
    '\tpublic static var BASE_BEACH:Array<Array<Array<Float>>> = %s;' % layout('beach'),
    '\tpublic static var BASE_DIRT:Array<Array<Array<Float>>> = %s;' % layout('dirt'),
    '\tpublic static var BASE_MOUNT:Array<Array<Array<Float>>> = %s;' % layout('mount'),
    '\t// mcCastle: placement of its base (x, y, yscale)',
    '\tpublic static var CASTLE_BASE:Array<Float> = %s;' % arr([float(v) for v in cb]),
    '\t// hit areas of the hex pictures (one per frame of hexB / hexD / hexM): top left (texture pixels from the',
    '\t// clip origin), then the rows of covered pixels, "start-end" runs',
    '\tpublic static var MASK_B:Array<HitMask> = %s;' % masks('hexB'),
    '\tpublic static var MASK_D:Array<HitMask> = %s;' % masks('hexD'),
    '\tpublic static var MASK_M:Array<HitMask> = %s;' % masks('hexM'),
    '\t// text fields: digits of the embedded Impact (anim, advances), text area x0..x1, first baseline, alignment, layers',
    '\t// of the field filters (anims anim_L0.., the glyph last)',
    '\tpublic static var DIG_INTER0:DigitsDef = %s;' % digits('digInter0'),
    '\tpublic static var DIG_INTER1:DigitsDef = %s;' % digits('digInter1'),
    '\tpublic static var DIG_CASTLE:DigitsDef = %s;' % digits('digCastle'),
    '\t// mcMsg: texts (frames of the anim msg), y of its smc on each frame (x = 150)',
    '\tpublic static var MSGS:Array<String> = [%s];' % ', '.join('"%s"' % s for s in meta['msgs']),
    '\tpublic static var MSG_Y:Array<Float> = %s;' % arr([float(v) for v in meta['msgY']]),
    '}',
    '',
    'typedef HitMask = {x:Int, y:Int, rows:String};',
    '',
    'typedef DigitsDef = {adv:Array<Float>, x0:Float, x1:Float, base:Float, align:String, anim:String, layers:Int};',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
