"""Writes resources/hx/games/memopsy/Data.hx from the meta.json of memopsy_assets.py.
usage: memopsy_data.py <out dir of memopsy_assets.py> <Data.hx>"""
import os, sys, json

OUT, DEST = sys.argv[1], sys.argv[2]
m = json.load(open(os.path.join(OUT, 'meta.json')))


def num(v):
    return repr(round(float(v), 6))


def arr(a):
    return '[' + ', '.join(num(v) for v in a) + ']'


def iarr(a):
    return '[' + ', '.join(str(int(v)) for v in a) + ']'


L = ['package memopsy;', '', '// generated by memopsy_data.py from the original SWF (do not edit)', 'class Data {']


def const(comment, name, typ, val, inline=False):
    if comment:
        L.append('\t// ' + comment)
    L.append('\tpublic static %svar %s:%s = %s;' % ('inline ' if inline else '', name, typ, val))


assert m['cardFrames'] == 11 and m['flipFrames'] == 9
const('card: 11 frames (1 the back, 2-11 the face with symbol 0-9)', 'CARD_FRAMES', 'Int', str(m['cardFrames']), True)
h = m['cardHit']
const('hit area of a card (shape 2, rounded corners): run-length rows (start, end, ...) at CARD_HIT_RES samples per '
      'Flash pixel from (CARD_HIT_X, CARD_HIT_Y)', 'CARD_HIT_X', 'Float', num(h['x0']), True)
const(None, 'CARD_HIT_Y', 'Float', num(h['y0']), True)
const(None, 'CARD_HIT_RES', 'Int', str(h['res']), True)
const(None, 'CARD_HIT', 'Array<Array<Int>>', '[' + ', '.join(iarr(r) for r in h['rows']) + ']')
f = m['flip']
const('flip (9 frames): on each frame, the nested card clips "back" (depth 1) and "top" (depth 4): x, y, xscale, '
      'grey multiplier (a tint) and whether it is shown (the placement\'s alpha multiplier, 0 or 1)',
      'FLIP_FRAMES', 'Int', str(m['flipFrames']), True)
const(None, 'FLIP_BACK', 'Array<Array<Float>>', '[' + ', '.join(arr(r) for r in f['back']) + ']')
const(None, 'FLIP_TOP', 'Array<Array<Float>>', '[' + ', '.join(arr(r) for r in f['top']) + ']')
const('life: l._width read by Game.addLife on the clip stopped at frame 1 (shape 34)', 'LIFE_WIDTH', 'Float',
      num(m['lifeWidth']), True)
L.append('}')
open(DEST, 'w').write('\n'.join(L) + '\n')
