<?php

namespace App\Services;

use App\Enums\ClanActionType;
use App\Enums\ClanBonusType;
use App\Exceptions\ClanException;
use App\Models\Clan;
use App\Models\ClanAction;
use App\Models\ClanBonus;
use App\Models\ClanMission;
use App\Models\ClanMissionStep;
use App\Models\Game;
use App\Models\Period;
use App\Models\Run;
use App\Models\User;
use Illuminate\Support\Facades\DB;

// the collaborative missions of the clans (news "New Clan Mode" of KadoKado, 2010-02-24): scores to reach on several
// games within kado.clans.mission_hours. Each step completed gives 1 point; all the steps completed in time double the
// points of the mission, otherwise the clan loses them. Each mission is harder than the previous one, with more steps.
class ClanMissionService
{
    public function __construct(private readonly ClanService $clanService) {}

    // the mission in progress (a new one when the previous is over)
    public function currentMission(Clan $clan, ?Period $period = null): ?ClanMission
    {
        $period ??= $this->clanService->currentPeriod();
        if (!$period) {
            return null;
        }

        $expired = ClanMission::query()
            ->where('clan_id', $clan->id)
            ->where('period_id', $period->id)
            ->where('status', ClanMission::ACTIVE)
            ->where('expires_at', '<=', now())
            ->get();
        foreach ($expired as $mission) {
            $this->loseMission($mission, ClanMission::FAILED);
        }

        $mission = ClanMission::query()
            ->where('clan_id', $clan->id)
            ->where('period_id', $period->id)
            ->where('status', ClanMission::ACTIVE)
            ->first();

        if (!$mission && $period->end_at->isFuture()) {
            $mission = $this->generateMission($clan, $period);
        }

        return $mission;
    }

    public function generateMission(Clan $clan, Period $period): ClanMission
    {
        return DB::transaction(function () use ($clan, $period) {
            $score = $this->clanService->periodScore($clan, $period);
            $score = $score->newQuery()->lockForUpdate()->find($score->id);
            // generated by another request in the meantime
            $active = ClanMission::query()->where('clan_id', $clan->id)->where('period_id', $period->id)
                ->where('status', ClanMission::ACTIVE)->where('expires_at', '>', now())->first();
            if ($active) {
                return $active;
            }

            $number = (int) ClanMission::query()->where('clan_id', $clan->id)->where('period_id', $period->id)->max('number') + 1;
            $mission = ClanMission::query()->create([
                'clan_id' => $clan->id,
                'period_id' => $period->id,
                'number' => $number,
                'status' => ClanMission::ACTIVE,
                'double_points' => $score->next_mission_double,
                'expires_at' => now()->addHours((int) config('kado.clans.mission_hours')),
            ]);
            if ($score->next_mission_double) {
                $score->update(['next_mission_double' => false]);
            }

            foreach ($this->pickGames($number, $score->banned_game_id, $score->forced_game_id) as $game) {
                $mission->steps()->create([
                    'game_id' => $game->id,
                    'target_score' => $this->targetScore($game, $number),
                    'points' => $mission->double_points ? 2 : 1,
                ]);
            }

            return $mission->load('steps');
        });
    }

    public function startStep(User $user, ClanMissionStep $step): ClanAction
    {
        $mission = $step->mission;
        $this->clanService->assertMember($user, $mission->clan);
        if ($mission->status !== ClanMission::ACTIVE || $mission->expires_at->isPast()) {
            throw new ClanException('Cette mission est terminée.');
        }
        if ($step->isDone()) {
            throw new ClanException('Cette étape a déjà été réussie.');
        }

        $this->clanService->forgetUnplayedActions($user);

        return ClanAction::query()->create([
            'clan_id' => $mission->clan_id,
            'user_id' => $user->id,
            'game_id' => $step->game_id,
            'type' => ClanActionType::MISSION,
            'clan_mission_step_id' => $step->id,
        ]);
    }

    // a step completed gives its point right away
    public function completeStep(ClanAction $action, Run $run): string
    {
        return DB::transaction(function () use ($action, $run) {
            $step = ClanMissionStep::query()->lockForUpdate()->findOrFail($action->clan_mission_step_id);
            $mission = ClanMission::query()->lockForUpdate()->findOrFail($step->clan_mission_id);

            if ($step->isDone() || $mission->status !== ClanMission::ACTIVE || $mission->expires_at->isPast()) {
                return 'too_late';
            }
            if ($run->score < $step->target_score) {
                return 'failed';
            }

            $step->update([
                'completed_by_user_id' => $action->user_id,
                'run_id' => $run->id,
                'score' => $run->score,
                'completed_at' => now(),
            ]);
            $mission->increment('points', $step->points);
            $this->clanService->periodScore($mission->clan, $mission->period)->increment('mission_score', $step->points);
            $this->clanService->memberStat($mission->clan_id, $action->user_id, $mission->period_id)->increment('mission_steps');
            $this->completeMissionIfDone($mission);

            return 'completed';
        });
    }

    // a mission not finished in time (or replaced by "Mission suivante", or left at the end of the period): the clan
    // loses the points of its completed steps
    public function loseMission(ClanMission $mission, string $status): void
    {
        DB::transaction(function () use ($mission, $status) {
            $mission = ClanMission::query()->lockForUpdate()->find($mission->id);
            if (!$mission || $mission->status !== ClanMission::ACTIVE) {
                return;
            }

            $score = $this->clanService->periodScore($mission->clan, $mission->period);
            $score->update(['mission_score' => max(0, $score->mission_score - $mission->points)]);
            $mission->update(['status' => $status]);
        });
    }

    // ---------------------------------------------------------------- bonuses

    /**
     * @param  array{game_id?: int, step_id?: int}  $params
     */
    public function useBonus(User $user, ClanBonus $bonus, array $params = []): void
    {
        $clan = $bonus->clan;
        $this->clanService->assertLeader($user, $clan);
        $this->assertUsable($bonus);
        if ($bonus->type->isAssignable()) {
            throw new ClanException('Cette option s\'utilise au moment d\'attaquer ou de défendre.');
        }
        $period = $this->clanService->assertPeriod();

        DB::transaction(function () use ($bonus, $clan, $period, $params) {
            $score = $this->clanService->periodScore($clan, $period);
            $mission = $this->currentMission($clan, $period);
            if (!$mission && in_array($bonus->type, [ClanBonusType::MORE_TIME, ClanBonusType::SKIP_STEP], true)) {
                throw new ClanException('Aucune mission en cours.');
            }

            switch ($bonus->type) {
                case ClanBonusType::NEXT_MISSION:
                    // a new mission without losing points: the steps completed in the replaced one give none either
                    if ($mission) {
                        $this->loseMission($mission, ClanMission::SKIPPED);
                    }
                    $this->generateMission($clan, $period);
                    break;
                case ClanBonusType::DOUBLE_POINTS:
                    $score->update(['next_mission_double' => true]);
                    break;
                case ClanBonusType::BAN_GAME:
                    $game = $this->activeGame($params['game_id'] ?? null);
                    $score->update([
                        'banned_game_id' => $game->id,
                        'forced_game_id' => $score->forced_game_id === $game->id ? null : $score->forced_game_id,
                    ]);
                    break;
                case ClanBonusType::FORCE_GAME:
                    $game = $this->activeGame($params['game_id'] ?? null);
                    $score->update([
                        'forced_game_id' => $game->id,
                        'banned_game_id' => $score->banned_game_id === $game->id ? null : $score->banned_game_id,
                    ]);
                    break;
                case ClanBonusType::MORE_TIME:
                    $mission->update(['expires_at' => $mission->expires_at->addHours((int) config('kado.clans.mission_more_time_hours'))]);
                    break;
                case ClanBonusType::SKIP_STEP:
                    // the step is removed: it gives no point
                    $step = $mission->steps()->whereKey($params['step_id'] ?? 0)->first();
                    if (!$step || $step->isDone()) {
                        throw new ClanException('Choisissez une étape de la mission en cours qui n\'est pas encore réussie.');
                    }
                    $step->update(['skipped' => true]);
                    $this->completeMissionIfDone($mission);
                    break;
                default:
                    break;
            }

            $bonus->update(['used_at' => now()]);
        });
    }

    // "Double attaque" and "Défense 120%" are given by the leader to a member, who uses it himself
    public function assignBonus(User $leader, ClanBonus $bonus, User $member): void
    {
        $this->clanService->assertLeader($leader, $bonus->clan);
        $this->assertUsable($bonus);
        if (!$bonus->type->isAssignable()) {
            throw new ClanException('Seules les options Double attaque et Défense 120% peuvent être données à un joueur.');
        }
        $this->clanService->assertMember($member, $bonus->clan);

        $bonus->update(['assigned_user_id' => $member->id]);
    }

    // ---------------------------------------------------------------- internals

    // all the steps done in time: the points of the mission are doubled, and the clan may win an option
    private function completeMissionIfDone(ClanMission $mission): void
    {
        $mission->refresh();
        if ($mission->steps()->get()->contains(fn (ClanMissionStep $step) => !$step->isDone())) {
            return;
        }

        $score = $this->clanService->periodScore($mission->clan, $mission->period);
        $score->increment('mission_score', $mission->points);
        $score->increment('missions_completed');
        $mission->update(['status' => ClanMission::COMPLETED, 'points' => $mission->points * 2, 'completed_at' => now()]);

        if (randomNumber() < (float) config('kado.clans.bonus_chance')) {
            $types = ClanBonusType::cases();
            ClanBonus::query()->create([
                'clan_id' => $mission->clan_id,
                'period_id' => $mission->period_id,
                'type' => $types[array_rand($types)],
            ]);
        }
    }

    private function assertUsable(ClanBonus $bonus): void
    {
        if ($bonus->used_at !== null) {
            throw new ClanException('Cette option a déjà été utilisée.');
        }
        if ($bonus->period_id !== $this->clanService->currentPeriod()?->id) {
            throw new ClanException('Les options sont remises à zéro à la fin du tournoi des clans.');
        }
    }

    private function activeGame(?int $gameId): Game
    {
        $game = $gameId ? Game::query()->where('is_active', true)->find($gameId) : null;
        if (!$game) {
            throw new ClanException('Choisissez un jeu.');
        }

        return $game;
    }

    // more steps with each mission
    private function stepsCount(int $number): int
    {
        $config = config('kado.clans.mission_steps');

        return min($config['max'], $config['min'] + intdiv($number - 1, $config['every']));
    }

    // harder with each mission: from half the green star to the red star (kado.clans.mission_difficulty_missions)
    private function targetScore(Game $game, int $number): int
    {
        $stars = collect($game->stars)->sort()->values();
        $difficulty = min(1, ($number - 1) / max(1, (int) config('kado.clans.mission_difficulty_missions')));
        $target = ($stars[0] / 2 + ($stars[2] - $stars[0] / 2) * $difficulty) * (0.9 + randomNumber() * 0.2);

        return max(1, (int) round($target));
    }

    /**
     * @return \Illuminate\Support\Collection<int, Game>
     */
    private function pickGames(int $number, ?int $bannedGameId, ?int $forcedGameId)
    {
        $games = Game::query()
            ->where('is_active', true)
            ->where('is_arkadeo', false)
            ->when($bannedGameId, fn ($q) => $q->where('id', '!=', $bannedGameId))
            ->get()
            ->filter(fn (Game $game) => is_array($game->stars) && count($game->stars) >= 3)
            ->shuffle();

        $forced = $forcedGameId ? $games->firstWhere('id', $forcedGameId) : null;
        if ($forced) {
            $games = $games->reject(fn (Game $game) => $game->id === $forced->id)->prepend($forced);
        }

        return $games->take($this->stepsCount($number))->values();
    }
}
