<?php

namespace App\Services;

use App\Enums\ClanActionType;
use App\Enums\ClanBonusType;
use App\Exceptions\ClanException;
use App\Models\Clan;
use App\Models\ClanAction;
use App\Models\ClanBonus;
use App\Models\ClanMission;
use App\Models\ClanMissionStep;
use App\Models\Game;
use App\Models\Period;
use App\Models\Run;
use App\Models\User;
use Illuminate\Support\Facades\DB;

// the collaborative missions of the clans: a score (a palier of the stars) to reach on several games within
// kado.clans.mission_hours, more games in a bigger clan, higher paliers with each mission. A completed mission gives up
// to 10 points (fewer with each mission) and opens the next one; a mission not finished in time loses 1 point by game
// not completed, minus one, and the clan gets a new mission of the same number. The runs of the missions are free.
class ClanMissionService
{
    public function __construct(private readonly ClanService $clanService) {}

    // the mission in progress (a new one when the previous is over)
    public function currentMission(Clan $clan, ?Period $period = null): ?ClanMission
    {
        $period ??= $this->clanService->currentPeriod();
        if (!$period) {
            return null;
        }

        $expired = ClanMission::query()
            ->where('clan_id', $clan->id)
            ->where('period_id', $period->id)
            ->where('status', ClanMission::ACTIVE)
            ->where('expires_at', '<=', now())
            ->get();
        foreach ($expired as $mission) {
            $this->loseMission($mission, ClanMission::FAILED);
        }

        $mission = ClanMission::query()
            ->where('clan_id', $clan->id)
            ->where('period_id', $period->id)
            ->where('status', ClanMission::ACTIVE)
            ->first();

        if (!$mission && $period->end_at->isFuture()) {
            $mission = $this->generateMission($clan, $period);
        }

        return $mission;
    }

    // the number of the mission: one more than the missions completed in the period
    public function generateMission(Clan $clan, Period $period): ClanMission
    {
        return DB::transaction(function () use ($clan, $period) {
            $score = $this->clanService->periodScore($clan, $period);
            $score = $score->newQuery()->lockForUpdate()->find($score->id);
            // generated by another request in the meantime
            $active = ClanMission::query()->where('clan_id', $clan->id)->where('period_id', $period->id)
                ->where('status', ClanMission::ACTIVE)->where('expires_at', '>', now())->first();
            if ($active) {
                return $active;
            }

            $number = $score->missions_completed + 1;
            $mission = ClanMission::query()->create([
                'clan_id' => $clan->id,
                'period_id' => $period->id,
                'number' => $number,
                'status' => ClanMission::ACTIVE,
                'expires_at' => now()->addHours((int) config('kado.clans.mission_hours')),
            ]);

            $steps = $this->stepsCount($clan->members()->count(), $number);
            foreach ($this->pickGames($steps, $score->banned_game_id, $score->forced_game_id) as $game) {
                $mission->steps()->create([
                    'game_id' => $game->id,
                    'target_score' => $this->targetScore($game, $number),
                ]);
            }

            return $mission->load('steps');
        });
    }

    public function startStep(User $user, ClanMissionStep $step): ClanAction
    {
        $mission = $step->mission;
        $this->clanService->assertMember($user, $mission->clan);
        if ($mission->status !== ClanMission::ACTIVE || $mission->expires_at->isPast()) {
            throw new ClanException('Cette mission est terminée.');
        }
        if ($step->isDone()) {
            throw new ClanException('Cette étape a déjà été réussie.');
        }

        $this->clanService->forgetUnplayedActions($user);

        return ClanAction::query()->create([
            'clan_id' => $mission->clan_id,
            'user_id' => $user->id,
            'game_id' => $step->game_id,
            'type' => ClanActionType::MISSION,
            'clan_mission_step_id' => $step->id,
        ]);
    }

    // a step completed gives a point to its player in the ranking of the clan
    public function completeStep(ClanAction $action, Run $run): string
    {
        return DB::transaction(function () use ($action, $run) {
            $step = ClanMissionStep::query()->lockForUpdate()->findOrFail($action->clan_mission_step_id);
            $mission = ClanMission::query()->lockForUpdate()->findOrFail($step->clan_mission_id);

            if ($step->isDone() || $mission->status !== ClanMission::ACTIVE || $mission->expires_at->isPast()) {
                return 'too_late';
            }
            if ($run->score < $step->target_score) {
                return 'failed';
            }

            $step->update([
                'completed_by_user_id' => $action->user_id,
                'run_id' => $run->id,
                'score' => $run->score,
                'completed_at' => now(),
            ]);
            $this->clanService->memberStat($mission->clan_id, $action->user_id, $mission->period_id)->increment('mission_steps');
            $this->completeMissionIfDone($mission);

            return 'completed';
        });
    }

    // not finished in time (or left at the end of the period): 1 point lost by step not completed, minus one. Replaced by
    // "Mission suivante": nothing lost.
    public function loseMission(ClanMission $mission, string $status): void
    {
        DB::transaction(function () use ($mission, $status) {
            $mission = ClanMission::query()->lockForUpdate()->find($mission->id);
            if (!$mission || $mission->status !== ClanMission::ACTIVE) {
                return;
            }

            $lost = 0;
            if ($status === ClanMission::FAILED) {
                $score = $this->clanService->periodScore($mission->clan, $mission->period);
                $missed = $mission->steps()->get()->reject(fn (ClanMissionStep $step) => $step->isDone())->count();
                $lost = min($score->mission_score, max(0, $missed - 1));
                $score->decrement('mission_score', $lost);
            }
            $mission->update(['status' => $status, 'points' => -$lost]);
        });
    }

    // the points of a completed mission: fewer with each mission
    public function missionPoints(int $number): int
    {
        $config = config('kado.clans.mission_points');

        return max((int) $config['min'], (int) round($config['first'] * $config['ratio'] ** ($number - 1)));
    }

    // the steps of a mission: more in a bigger clan, (maybe) fewer with each mission
    public function stepsCount(int $membersCount, int $number): int
    {
        $config = config('kado.clans.mission_steps');
        $base = min($config['max'], $config['base'] + max(0, $membersCount - 1) * $config['per_member']);

        return max((int) $config['min'], (int) round($base * $config['ratio'] ** ($number - 1)));
    }

    // ---------------------------------------------------------------- bonuses

    /**
     * @param  array{game_id?: int, step_id?: int}  $params
     */
    public function useBonus(User $user, ClanBonus $bonus, array $params = []): void
    {
        $clan = $bonus->clan;
        $this->clanService->assertManager($user, $clan);
        $this->assertUsable($bonus);
        $period = $this->clanService->assertPeriod();

        DB::transaction(function () use ($bonus, $clan, $period, $params) {
            $score = $this->clanService->periodScore($clan, $period);
            $mission = $this->currentMission($clan, $period);
            if (!$mission && in_array($bonus->type, [ClanBonusType::MORE_TIME, ClanBonusType::SKIP_STEP], true)) {
                throw new ClanException('Aucune mission en cours.');
            }

            switch ($bonus->type) {
                case ClanBonusType::NEXT_MISSION:
                    // a new mission of the same number, without losing points
                    if ($mission) {
                        $this->loseMission($mission, ClanMission::SKIPPED);
                    }
                    $this->generateMission($clan, $period);
                    break;
                case ClanBonusType::BAN_GAME:
                    $game = $this->activeGame($params['game_id'] ?? null);
                    $score->update([
                        'banned_game_id' => $game->id,
                        'forced_game_id' => $score->forced_game_id === $game->id ? null : $score->forced_game_id,
                    ]);
                    break;
                case ClanBonusType::FORCE_GAME:
                    $game = $this->activeGame($params['game_id'] ?? null);
                    $score->update([
                        'forced_game_id' => $game->id,
                        'banned_game_id' => $score->banned_game_id === $game->id ? null : $score->banned_game_id,
                    ]);
                    break;
                case ClanBonusType::MORE_TIME:
                    $mission->update(['expires_at' => $mission->expires_at->addHours((int) config('kado.clans.mission_more_time_hours'))]);
                    break;
                case ClanBonusType::SKIP_STEP:
                    $step = $mission->steps()->whereKey($params['step_id'] ?? 0)->first();
                    if (!$step || $step->isDone()) {
                        throw new ClanException('Choisissez une étape de la mission en cours qui n\'est pas encore réussie.');
                    }
                    $step->update(['skipped' => true]);
                    $this->completeMissionIfDone($mission);
                    break;
            }

            $bonus->update(['used_at' => now()]);
        });
    }

    // ---------------------------------------------------------------- internals

    // all the steps done in time: the points of the mission, maybe an option, and the next mission
    private function completeMissionIfDone(ClanMission $mission): void
    {
        $mission->refresh();
        if ($mission->steps()->get()->contains(fn (ClanMissionStep $step) => !$step->isDone())) {
            return;
        }

        $points = $this->missionPoints($mission->number);
        $score = $this->clanService->periodScore($mission->clan, $mission->period);
        $score->increment('mission_score', $points);
        $score->increment('missions_completed');
        $mission->update(['status' => ClanMission::COMPLETED, 'points' => $points, 'completed_at' => now()]);

        if (randomNumber() < (float) config('kado.clans.bonus_chance')) {
            ClanBonus::query()->create([
                'clan_id' => $mission->clan_id,
                'period_id' => $mission->period_id,
                'type' => $this->randomBonusType(),
            ]);
        }
    }

    // by the chances of kado.clans.bonus_weights
    private function randomBonusType(): ClanBonusType
    {
        $weights = collect(ClanBonusType::cases())
            ->mapWithKeys(fn (ClanBonusType $type) => [$type->value => max(0, (float) config("kado.clans.bonus_weights.{$type->value}", 0))]);
        $draw = randomNumber() * $weights->sum();
        foreach ($weights as $type => $weight) {
            $draw -= $weight;
            if ($draw < 0) {
                return ClanBonusType::from($type);
            }
        }

        return ClanBonusType::from($weights->keys()->last());
    }

    private function assertUsable(ClanBonus $bonus): void
    {
        if ($bonus->used_at !== null) {
            throw new ClanException('Cette option a déjà été utilisée.');
        }
        if ($bonus->period_id !== $this->clanService->currentPeriod()?->id) {
            throw new ClanException('Les options sont remises à zéro à la fin du tournoi des clans.');
        }
    }

    private function activeGame(?int $gameId): Game
    {
        $game = $gameId ? Game::query()->where('is_active', true)->find($gameId) : null;
        if (!$game) {
            throw new ClanException('Choisissez un jeu.');
        }

        return $game;
    }

    // a palier of the stars of the game, one higher every kado.clans.mission_paliers_every missions: half the first star,
    // the first star, between the first and the second, the second... up to the last star
    private function targetScore(Game $game, int $number): int
    {
        $stars = collect($game->stars)->sort()->values();
        $paliers = [];
        foreach ($stars as $index => $star) {
            $paliers[] = $index === 0 ? $star / 2 : ($stars[$index - 1] + $star) / 2;
            $paliers[] = $star;
        }
        $palier = min(count($paliers) - 1, intdiv($number - 1, max(1, (int) config('kado.clans.mission_paliers_every'))));

        return max(1, (int) round($paliers[$palier]));
    }

    /**
     * @return \Illuminate\Support\Collection<int, Game>
     */
    private function pickGames(int $count, ?int $bannedGameId, ?int $forcedGameId)
    {
        $games = Game::query()
            ->where('is_active', true)
            ->where('is_arkadeo', false)
            ->when($bannedGameId, fn ($q) => $q->where('id', '!=', $bannedGameId))
            ->get()
            ->filter(fn (Game $game) => is_array($game->stars) && count($game->stars) >= 3)
            ->shuffle();

        $forced = $forcedGameId ? $games->firstWhere('id', $forcedGameId) : null;
        if ($forced) {
            $games = $games->reject(fn (Game $game) => $game->id === $forced->id)->prepend($forced);
        }

        return $games->take($count)->values();
    }
}
