"""Writes electrolink/Data.hx from the asset pipeline output (meta.json).
usage: electrolink_data.py <out dir of electrolink_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def arr(v):
    return '[' + ', '.join(repr(x) for x in v) + ']'


def hexes(v):
    return '[' + ', '.join('0x%06X' % c for c in v) + ']'


def filt(f):
    r, g, b, a = f['color']
    return '{blur: %r, strength: %r, passes: %d, color: 0x%06X}' % (f['blurX'], f['strength'], f['passes'], (r << 16) | (g << 8) | b)


sc = meta['scoring']
tx = meta['text']
fields = tx['fields']
sp = meta['sparks']
pts = fields['_pts']
mult = fields['_mult']
assert [f['type'] for f in pts['filters']] == ['glow', 'dropshadow'] and pts['filters'] == mult['filters']
assert pts['filters'][1]['distance'] == 0 and not any(f['inner'] or f['knockout'] for f in pts['filters'])
lines = [
    'package electrolink;',
    '',
    '// generated by electrolink_data.py from the original SWF (do not edit)',
    'class Data {',
    '\t// colours of the 80 frames of the green / blue pulse (color clip, frames 2 and 3: morph shapes)',
    '\tpublic static var PULSE_GREEN:Array<Int> = %s;' % hexes(meta['pulseGreen']),
    '\tpublic static var PULSE_BLUE:Array<Int> = %s;' % hexes(meta['pulseBlue']),
    '\t// tile hover glow pictures "hover<i>": rotation (degrees, mod 90) and scale of the tile they were computed for',
    '\tpublic static var HOVER_ROT:Array<Float> = %s;' % arr([float(h[0]) for h in meta['hover']]),
    '\tpublic static var HOVER_SCALE:Array<Float> = %s;' % arr([float(h[1]) for h in meta['hover']]),
    '\t// hit area of the tile buttons (shape 8: xmin, xmax, ymin, ymax)',
    '\tpublic static var TILE_HIT:Array<Float> = %s;' % arr([float(v) for v in meta['tileHit']]),
    '\t// texture pixels per unit of the goal pictures (the goal is drawn at 70 %)',
    '\tpublic static inline var GOAL_RES = %r;' % meta['goalRes'],
    '\t// timeLeft: _width / _height at 100 %',
    '\tpublic static inline var TIME_LEFT_W = %r;' % float(meta['timeLeft'][0]),
    '\tpublic static inline var TIME_LEFT_H = %r;' % float(meta['timeLeft'][1]),
    '\t// part1 pictures "part<sy>": vertical scales (percent) baked in the textures',
    '\tpublic static var PART_SCALES:Array<Int> = %s;' % arr(meta['partScales']),
    '\t// mcBg sparks: anim "spark<i>" (2 pictures per frame: frame of the path, frame of part1), frames of the path,',
    '\t// odds of the controller (random(n) + base == base + 1 every frame)',
    '\tpublic static var SPARK_FRAMES:Array<Int> = %s;' % arr([s['frames'] for s in sp]),
    '\tpublic static var SPARK_ODDS:Array<Int> = %s;' % arr([s['odds'] for s in sp]),
    '\t// scoring timeline: _t x, alpha and BlurFilter blurX for each of its 27 frames (stop() on the last one)',
    '\tpublic static var SCORING_X:Array<Float> = %s;' % arr(sc['tx']),
    '\tpublic static var SCORING_ALPHA:Array<Float> = %s;' % arr(sc['alpha']),
    '\tpublic static var SCORING_BLUR:Array<Float> = %s;' % arr(sc['blur']),
    '\t// TexasLED glyphs (anim "glyph", in this order): advances and ascent at the size of the fields',
    '\tpublic static inline var GLYPHS = "%s";' % tx['chars'],
    '\tpublic static var GLYPH_ADV:Array<Float> = %s;' % arr(tx['adv']),
    '\tpublic static inline var GLYPH_ASCENT = %r;' % tx['ascent'],
    '\t// text fields of _t: rectangle (x, y, width), right aligned or not, colour',
    '\tpublic static var FIELD_PTS = {x: %r, y: %r, w: %r, right: %s, color: 0x%06X};' % (
        round(pts['x'], 4), round(pts['y'], 4), round(pts['w'], 4), 'true' if pts['align'] == 'right' else 'false', pts['color']),
    '\tpublic static var FIELD_MULT = {x: %r, y: %r, w: %r, right: %s, color: 0x%06X};' % (
        round(mult['x'], 4), round(mult['y'], 4), round(mult['w'], 4), 'true' if mult['align'] == 'right' else 'false', mult['color']),
    '\t// filters of both fields: GlowFilter then DropShadowFilter (distance 0)',
    '\tpublic static var FIELD_GLOW = %s;' % filt(pts['filters'][0]),
    '\tpublic static var FIELD_SHADOW = %s;' % filt(pts['filters'][1]),
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
