"""Writes julianus/Data.hx from the asset pipeline output (meta.json).
usage: julianus_data.py <out dir of julianus_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def num(x):
    if isinstance(x, int) or float(x).is_integer():
        return repr(float(x))
    return repr(round(float(x), 10))


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return num(v)


def flat(v):
    out = []
    for x in v:
        out += flat(x) if isinstance(x, list) else [x]
    return out


dec = meta['decor']
lines = [
    'package julianus;',
    '',
    '// generated by julianus_data.py from the original SWF (do not edit)',
    'class Data {',
    '\t// placements of children in their parent: x, y, _xscale, _yscale (negative: mirrored), _rotation',
    '\t// hero.body (sprite 9 in hero)',
    '\tpublic static var BODY:Array<Float> = %s;' % arr(meta['body']),
    '\t// blow, per frame (60: one per direction), its 3 puffs: depth 1 (puff), depth 3 (puff), depth 5 (puffEnd)',
    '\tpublic static var BLOW:Array<Float> = %s;' % arr(flat(meta['blow'])),
    '\t// pic frame 3: its "sub" ball where the timeline places it (the code moves it)',
    '\tpublic static var PIC2_SUB:Array<Float> = %s;' % arr(meta['pic2Sub']),
    '\t// resolutions of the bubble pictures (bulle25, bulle50, bulle100) and of its burst (pop25, pop50), in scale',
    '\tpublic static var BULLE_LEVELS:Array<Float> = %s;' % arr(meta['bulleLevels']),
    '\tpublic static var POP_LEVELS:Array<Float> = %s;' % arr(meta['popLevels']),
    '\t// decor planes: _width of the shape (the code wraps it every _width / 2), bitmaps (anim, x, y) drawn at x and',
    '\t// x + 600',
]
for name in ('bg2', 'bg1', 'bg0'):
    d = dec[name]
    lines.append('\tpublic static inline var %s_WIDTH = %s;' % (name.upper(), num(d['width'])))
    lines.append('\tpublic static var %s_PARTS:Array<Dynamic> = %s;' % (
        name.upper(), '[' + ', '.join('["%s", %s, %s]' % (p[0], num(p[1]), num(p[2])) for p in d['parts']) + ']'))
lines.append('}')
open(DST, 'w').write('\n'.join(lines) + '\n')
