"""Writes spiroule/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: spiroule_data.py <out dir of spiroule_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


f = meta['multiField']
lines = [
    'package spiroule;',
    '',
    '// generated by spiroule_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// fxSpark with its glow (anim "spark"): frame type (0: the star of frame 1, 1: the dot) x SPARK_STEPS + scale step',
    '\t// - 1, the picture of scale (step / SPARK_STEPS); FX_SPARK_FRAMES frames in the timeline of fxSpark',
    '\tpublic static inline var SPARK_STEPS = %d;' % meta['sparkSteps'],
    '\tpublic static inline var SPARK_FRAMES = %d;' % meta['sparkFrames'],
    '',
    '\t// mcMulti.smc\'s text field (Severina 20, centred): its text area (x, width) and first baseline in smc; the',
    '\t// advances of "x0123456789"; the glyphs (anim "multiDig") are drawn at MULTI_GLYPH_RES x 2 px per Flash pixel',
    '\tpublic static inline var MULTI_X = %r;' % float(f['x']),
    '\tpublic static inline var MULTI_W = %r;' % float(f['w']),
    '\tpublic static inline var MULTI_BASE = %r;' % float(f['base']),
    '\tpublic static var MULTI_ADV:Array<Float> = %s;' % arr(meta['multiAdv']),
    '\tpublic static inline var MULTI_GLYPH_RES = %r;' % float(meta['multiGlyphRes']),
    '\t// BlurFilter of mcMulti.smc on each frame (stage pixels, one box: quality 1)',
    '\tpublic static var MULTI_BLUR:Array<Float> = %s;' % arr(meta['multiBlur']),
    '',
    '\t// pixels of the pictures mcBall2.smc and mcMulti.smc per Flash pixel (what the game draws in them)',
    '\tpublic static inline var BALL_SMC_K = %r;' % float(meta['ballSmcK']),
    '\tpublic static inline var MULTI_SMC_K = %r;' % float(meta['multiSmcK']),
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
