"""Writes kslash/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: kslash_data.py <out dir of kslash_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def arr(v):
    return '[' + ', '.join(repr(x) for x in v) + ']'


def digits(key):
    d = meta[key]
    return '{anim: "%s", adv: %s, x: %r, w: %r, base: %r, center: %s}' % (
        key, arr(d['adv']), d['x'], d['w'], d['base'], 'true' if d['center'] else 'false')


def decor(frames):
    # per frame: bitmaps [id, a, b, c, d, tx, ty]
    return '[' + ', '.join('[' + ', '.join('[%s]' % ', '.join(repr(float(v)) for v in b) for b in fr) + ']' for fr in frames) + ']'


plat = {p['name'] or ('corner0' if p['d'] == 9 else 'text'): p for p in meta['plat']}
lines = [
    'package kslash;',
    '',
    '// generated by tools/kslash_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// decor sprites bg (day, night), bgFront (3 frames), bgBack: per frame, the bitmaps of their shapes',
    '\t// [bitmap id (anim "decor" + id), a, b, c, d, tx, ty] in Flash pixels',
    '\tpublic static var DECOR_BG:Array<Array<Array<Float>>> = %s;' % decor(meta['decor']['bg']),
    '\tpublic static var DECOR_FRONT:Array<Array<Array<Float>>> = %s;' % decor(meta['decor']['bgFront']),
    '\tpublic static var DECOR_BACK:Array<Array<Array<Float>>> = %s;' % decor(meta['decor']['bgBack']),
    '\t// _width of the frames of bgFront and bgBack (Game.new: c = (_width - 300) / 300)',
    '\tpublic static var FRONT_WIDTH = %s;' % arr(meta['frontWidth']),
    '\tpublic static var BACK_WIDTH = %s;' % arr(meta['backWidth']),
    '\t// mcPlat: mask (x, y, height of the 100 px wide mask), texture strip (x, y), corners (x)',
    '\tpublic static inline var PLAT_MASK_X = %r;' % plat['mask']['x'],
    '\tpublic static inline var PLAT_MASK_Y = %r;' % plat['mask']['y'],
    '\tpublic static inline var PLAT_MASK_H = %r;' % (meta['platMaskBounds'][3] - meta['platMaskBounds'][2]),
    '\tpublic static inline var PLAT_TEXT_X = %r;' % plat['text']['x'],
    '\tpublic static inline var PLAT_TEXT_Y = %r;' % plat['text']['y'],
    '\tpublic static inline var PLAT_CORNER_X = %r;' % plat['corner0']['x'],
    '\t// numbers of the text fields (star counter, score popups): digits of the fonts embedded in the SWF, Flash',
    '\t// layout in Flash pixels relative to their clip (left of the field, width, baseline, centred or not)',
    '\tpublic static var DIGIT_STAR:Digits.DigitsDef = %s;' % digits('digitStar'),
    '\tpublic static var DIGIT_SCORE:Digits.DigitsDef = %s;' % digits('digitScore'),
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
