version: '3'
services:
  kadokadeo_app:
    build:
        context: .
        dockerfile: docker/app/Dockerfile
    container_name: kadokadeo_app
    volumes:
      - .:/www
    networks:
      - kadokadeo_network
    links:
      - kadokadeo_database

  kadokadeo_front:
    image: node:20
    container_name: kadokadeo_front
    volumes:
      - .:/www
    working_dir: /www
    command: 'sh -c "yarn && yarn dev"'

  kadokadeo_database:
    image: postgres:15.1
    container_name: kadokadeo_database
    volumes:
      - ./docker/database:/docker-entrypoint-initdb.d
    networks:
      - kadokadeo_network
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: kadokadeo.dev
      POSTGRES_MULTIPLE_DATABASES: kadokadeo,etwin.dev

  kadokadeo_eternaltwin:
    container_name: kadokadeo_eternaltwin
    build:
      context: ./docker/eternaltwin
      dockerfile: Dockerfile
    volumes:
      - ./eternaltwin:/www
    networks:
      - kadokadeo_network
    stdin_open: true
    tty: true

  kadokadeo_nginx:
    depends_on:
      - kadokadeo_app
    networks:
      - kadokadeo_network
    container_name: kadokadeo_nginx
    image: nginx:1.21
    volumes:
      - ./docker/app/conf/kadokadeo.conf:/etc/nginx/conf.d/kadokadeo.conf:ro
      - ./:/www

networks:
  kadokadeo_network:
    driver: bridge
