"""Writes oursouinvader/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: oursouinvader_data.py <out dir of oursouinvader_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


w = meta['wave']
lines = [
    'package oursouinvader;',
    '',
    '// generated by oursouinvader_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// mcScore with its text (the values of Game.dispScore) and its glow baked: clip "score<value>"',
    '\tpublic static var SCORES:Array<Int> = [%s];' % ', '.join(str(v) for v in meta['scores']),
    '',
    '\t// mcLevelDisplay.field ("Sweet as candy" %g, centred): glyphs (anim "waveGlyphs", white) of WAVE_CHARS, their' % 24,
    '\t// advances, the text area and the first baseline in the clip, the colour of the text',
    '\tpublic static var WAVE:Txt.TxtDef = {',
    '\t\tanim: "waveGlyphs",',
    '\t\tchars: "%s",' % w['chars'],
    '\t\tadv: %s,' % arr(w['adv']),
    '\t\tx: %r,' % float(w['x']),
    '\t\tw: %r,' % float(w['w']),
    '\t\tbase: %r,' % float(w['base']),
    '\t\tcenter: true',
    '\t};',
    '\tpublic static inline var WAVE_COLOR = 0x%06X;' % w['color'],
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
