package hypercube;

// generated by hypercube_data.py from the original SWF (do not edit)
class Data {
	// bg.ray: position, _alpha (the stripes of the conveyor, 320 x 64, 1 texture pixel per Flash pixel)
	public static inline var RAY_X:Float = 0.55;
	public static inline var RAY_Y:Float = 6.7;
	public static inline var RAY_ALPHA:Float = 10.15625;
	// bg.horloge: position, scale, _alpha; texture pixels per unit of its ha pictures (166 frames)
	public static inline var HORLOGE_X:Float = 150.0;
	public static inline var HORLOGE_Y:Float = 37.5;
	public static inline var HORLOGE_SCALE:Float = 89.99939;
	public static inline var HORLOGE_ALPHA:Float = 19.921875;
	public static inline var HA_RES:Float = 1.799988;
	// hit area of a cube for each frame of its sub (xmin, xmax, ymin, ymax in the cube)
	public static var CUBE_HIT:Array<Array<Float>> = [[-7.5, 7.5, -15.0, 7.5], [-7.5, 7.5, -15.0, 7.5], [-7.5, 7.5, -15.0, 7.5], [-7.5, 7.5, -15.0, 7.5], [-7.45, 7.55, -15.0, 7.5], [-7.5, 7.5, -15.0, 7.5], [-7.45, 7.55, -15.0, 7.5], [-7.45, 7.55, -15.0, 7.5], [-7.5, 7.5, -15.0, 7.5], [-7.5, 7.5, -15.0, 7.5], [-7.5, 7.5, -15.0, 7.5], [-7.5, 7.5, -15.0, 7.5], [-7.45, 7.55, -15.0, 7.5], [-7.45, 7.55, -15.0, 7.5], [-7.45, 7.55, -15.0, 7.5], [-7.45, 7.55, -15.0, 7.5]];
	// cubLight in the cube (frames 4-6)
	public static inline var CUBLIGHT_X:Float = -0.05;
	public static inline var CUBLIGHT_Y:Float = 0.0;
	// butExt: hit area added to the cubes of the conveyor (alpha 0)
	public static var BUT_EXT:Array<Float> = [-21.0, 21.0, -21.0, 21.0];
	// partQueue: _alpha of its line on each of its 21 frames (t = 0 on the last one)
	public static var QUEUE_ALPHA:Array<Float> = [100.0, 94.921875, 89.84375, 85.15625, 80.078125, 75.0, 69.921875, 64.84375, 60.15625, 55.078125, 50.0, 44.921875, 39.84375, 35.15625, 30.078125, 25.0, 19.921875, 14.84375, 10.15625, 5.078125, 0.0];
	// partRound: frames (removeMovieClip on the last one)
	public static inline var ROUND_FRAMES:Int = 12;
	// scoreSquare: position of bg; scale (percent) above which bg uses its big picture (squareBgBig)
	public static inline var SQUARE_BG_X:Float = 0.05;
	public static inline var SQUARE_BG_Y:Float = 0.0;
	public static inline var SQUARE_BIG:Float = 210.0;
	// score field of scoreSquare.sf (Arcade Classic 20, y scale baked in the "digit" pictures): advances, text area (x0, x1) and first baseline in sf; sf position
	public static var DIGIT_ADV:Array<Float> = [16.5234, 14.2773, 16.5234, 16.5234, 16.5234, 16.5234, 16.5234, 16.5234, 16.5234, 16.5234];
	public static inline var DIGIT_X0:Float = -61.1;
	public static inline var DIGIT_X1:Float = 60.3;
	public static inline var DIGIT_BASE:Float = 20.2146;
	public static inline var SF_X:Float = 51.55;
	public static inline var SF_Y:Float = 47.7;
	// mcScore: y of its score panel on frames 1-21 (frame 22 removes the clip)
	public static var SCORE_Y:Array<Float> = [28.5, 25.65, 22.8, 19.95, 17.1, 14.25, 11.4, 8.55, 5.7, 2.85, 0.0, 2.85, 5.7, 8.55, 11.4, 14.25, 17.1, 19.95, 22.8, 25.65, 28.5];
	// butEndGame: hit area of smc (shape 15, in butEndGame), _alpha of the text on its 21 frames (looping)
	public static var END_HIT:Array<Float> = [0.0, 300.0, 4.0, 76.0];
	public static var END_TEXT_ALPHA:Array<Float> = [100.0, 99.609375, 98.046875, 95.3125, 92.1875, 87.5, 82.03125, 75.390625, 67.96875, 59.375, 50.0, 59.375, 67.96875, 75.390625, 82.03125, 87.5, 92.1875, 95.3125, 98.046875, 99.609375, 100.0];
}
