"""Writes paradice/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: paradice_data.py <out dir of paradice_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def num(v):
    return repr(float(v))


def field(f):
    return '{anim: "%s", chars: "%s", adv: [%s], x: %s, w: %s, base: %s, center: %s}' % (
        f['anim'], f['chars'], ', '.join(num(a) for a in f['adv']), num(f['x']), num(f['w']), num(f['base']),
        'true' if f['center'] else 'false')


lines = [
    'package paradice;',
    '',
    '// generated by paradice_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// text fields (see Txt), in Flash pixels of their clip: "field" of mcScoreBubble (Impact, embedded) and',
    '\t// "_parent.score" of the board of mcMultiPanel (Verdana Bold Italic, a device font)',
    '\tpublic static var BUBBLE_FIELD:Txt.TxtDef = %s;' % field(meta['bubbleField']),
    '\tpublic static var PANEL_FIELD:Txt.TxtDef = %s;' % field(meta['panelField']),
    '\t// _width of the bubble of mcScoreBubble at 100 % (its first frame)',
    '\tpublic static var BUBBLE_W:Float = %s;' % num(meta['bubbleW']),
    '\t// texture pixels per Flash pixel of the board picture of mcMultiPanel (a bitmap at its native resolution)',
    '\tpublic static var BOARD_RES:Float = %s;' % num(meta['boardRes']),
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
