"""Writes logico/Data.hx from the asset pipeline output (meta.json).
usage: logico_data.py <out dir of logico_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def arr(v):
    return '[' + ', '.join(repr(x) for x in v) + ']'


sf = meta['scoreField']
lines = [
    'package logico;',
    '',
    '// generated by logico_data.py from the original SWF (do not edit)',
    'class Data {',
    '\t// hit area of the ball buttons, per colour: radius of the union of its shapes (circles on the origin)',
    '\tpublic static var BALL_HIT:Array<Float> = %s;' % arr([float(v) for v in meta['ballHit']]),
    '\t// pictures "ballCombo" per colour: one per value of tcoef below 1 in Game.updateCombo',
    '\tpublic static inline var COMBO_STEPS = %d;' % meta['comboSteps'],
    '\t// frames of the partJunk timeline',
    '\tpublic static inline var JUNK_FRAMES = %d;' % meta['junkFrames'],
    '\t// mcScore.field: glyphs (anims "glyph" and "glyphGlow", in this order), advances, right edge of the text',
    '\t// (right aligned) and baseline, in the coordinates of mcScore',
    '\tpublic static inline var SCORE_CHARS = "%s";' % sf['chars'],
    '\tpublic static var SCORE_ADV:Array<Float> = %s;' % arr(sf['adv']),
    '\tpublic static inline var SCORE_RIGHT = %r;' % float(sf['right']),
    '\tpublic static inline var SCORE_BASE = %r;' % float(sf['base']),
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
