"""Happy Pti Tank: <out>/data.json (happyptitank_assets.py) -> resources/hx/games/happyptitank/Data.hx
usage: happyptitank_data.py <out dir> <Data.hx>"""
import json, sys

out_dir, dest = sys.argv[1], sys.argv[2]
d = json.load(open(out_dir + '/data.json'))
raw = json.dumps(d, separators=(',', ':'), sort_keys=True)
assert "'" not in raw and '\\' not in raw.replace('\\"', '')
pal = ', '.join('0x%06X' % c for c in d['palette'])
src = '''package happyptitank;

// GENERATED by .opencode/skills/flash-port/scripts/examples/happyptitank/happyptitank_data.py from tank.swf
// (happyptitank_assets.py): do not edit, rebuild with rebuild_assets.sh.
//
// J.symbols[sid]: {frames: [[entries]], idx: [frame -> index in frames], cls}, an entry being
//   [kind ("M" clip / "L" leaf / "F" text field / "E" empty clip), ref, key, a, b, c, d, tx, ty, cx index, name index,
//    clipDepth, fx index, variant]
// J.leaves[name]: {res, ox, oy, w, h, b: bounds [x0, x1, y0, y1], r: edge bounds, mask, mox, moy, white, tiles}
// J.masks[i]: {w, h, rle} (4 samples per Flash pixel), J.cx / J.names / J.fx: tables, J.variants[name]: 9 leaves
class Data {
	// ColorSet: the 9 colours of the squares of symbol 86 (getPixel(5 + 10 n, 5))
	public static var PALETTE:Array<Int> = [%s];

	static var j:Dynamic = null;

	public static function get():Dynamic {
		if (j == null)
			j = haxe.Json.parse(RAW);
		return j;
	}

	static inline var RAW = '%s';
}
''' % (pal, raw)
open(dest, 'w').write(src)
print('Data.hx', len(src))
