package linea;

// generated by linea_data.py from the original SWF (do not edit)
class Data {
	// _width / _height of mcSquare (every frame) and mcBonus
	public static inline var SQUARE_W = 40.0;
	public static inline var SQUARE_H = 40.0;
	public static inline var BONUS_W = 8.2;
	public static inline var BONUS_H = 39.2;
	// _width / _height of mcAddline for each frame of its nested mcAniglow (the ring grows: twips)
	public static var ADDLINE_W:Array<Float> = [21.0, 22.5, 24.3, 26.0, 27.7, 29.5, 31.2, 33.3, 35.4, 37.4, 39.5, 41.6];
	public static var ADDLINE_H:Array<Float> = [21.0, 22.5, 24.3, 26.0, 27.7, 29.5, 31.2, 33.3, 35.4, 37.4, 39.5, 41.6];
	// mcBonus: its mcSoloBonus children in depth order: name, x, y
	public static var STARS_NAME = ["b4", "b1", "b2", "b3"];
	public static var STARS_X:Array<Float> = [5.6, 5.6, 5.6, 5.6];
	public static var STARS_Y:Array<Float> = [33.0, 2.0, 12.0, 22.0];
	// mcBack (bitmap at its native resolution)
	public static inline var BACK_W = 600;
	public static inline var BACK_H = 400;
	// colours baked in the bonus stars and their particles (anims "star" / "bpart" + RRGGBB)
	public static var COLORS:Array<Int> = [0x00AABD, 0x00B1AE, 0x2CB431, 0x5EBD47, 0x70C7D4, 0x7DC622, 0x9681B7, 0xA11135, 0xA32F75, 0xBBDB88, 0xBF0222, 0xBFB1D3, 0xC56B23, 0xCDD00A, 0xCF0226, 0xD45521, 0xDC97A1, 0xE20078, 0xF1AF00, 0xF3C200, 0xF5D300, 0xF9F400, 0xFA7236, 0xFEF886, 0xFFD572];
	// values of the text fields rendered from the SWF (frame n = value n)
	public static inline var DFACTOR_MAX = 12;
	public static inline var LINE_SCORE_MAX = 4;
	public static inline var MULT_MAX = 3;
}
