"""Writes magmax/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: magmax_data.py <out dir of magmax_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


lines = [
    'package magmax;',
    '',
    '// generated by magmax_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// Bounds read by the hitTests (Flash: every shape rectangle through its full matrix), [xMin, xMax, yMin, yMax]',
    '\t// in Flash pixels of the clip the code moves.',
    '\t// hero.mc.col (the same on every frame of the hero)',
    '\tpublic static var HERO_COL:Array<Float> = %s;' % arr(meta['heroCol']),
    '\t// monster.mc.sub.col: [type][frame of sub - 1]',
    '\tpublic static var MONSTER_COL:Array<Array<Array<Float>>> = %s;' % arr(meta['monsterCol']),
    '\t// tir: [frame - 1][frame of its nested clip - 1] -> shapes [xMin, xMax, yMin, yMax, a, b, c, d, tx, ty] (matrix',
    '\t// in the tir), turned by its _rotation at run time',
    '\tpublic static var TIR_LEAVES:Array<Array<Array<Array<Float>>>> = %s;' % arr(meta['tirLeaves']),
    '\t// bonus frames 1-3: [frame of the gem - 1]; frames 4-5: sprites 16 and 19 [their frame - 1], option particles',
    '\t// [copy i (turned by 60 * i deg)][frame - 1]',
    '\tpublic static var BONUS_GEM:Array<Array<Float>> = %s;' % arr(meta['bonusGem']),
    '\tpublic static var BONUS_16:Array<Array<Float>> = %s;' % arr(meta['bonus16']),
    '\tpublic static var BONUS_19:Array<Array<Float>> = %s;' % arr(meta['bonus19']),
    '\tpublic static var BONUS_PART:Array<Array<Array<Float>>> = %s;' % arr(meta['bonusPart']),
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
