"""Writes cerealpunk/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: cerealpunk_data.py <out dir of cerealpunk_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


d = meta['digits']
lines = [
    'package cerealpunk;',
    '',
    '// generated by cerealpunk_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// fieldScore.sc text field (Impact 18, right aligned): digits (anim "digits" at DIGITS_RES), advances, right edge',
    '\t// of the text and first baseline in sc',
    '\tpublic static var DIGITS_ADV:Array<Float> = %s;' % arr(d['adv']),
    '\tpublic static inline var DIGITS_RIGHT = %r;' % float(d['right']),
    '\tpublic static inline var DIGITS_BASE = %r;' % float(d['base']),
    '\tpublic static inline var DIGITS_RES = %r;' % float(d['res']),
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
