"""Writes resources/hx/games/toymaniak/Data.hx from the meta.json of toymaniak_assets.py.
usage: toymaniak_data.py <out dir of toymaniak_assets.py> <Data.hx>"""
import os, sys, json

OUT, DEST = sys.argv[1], sys.argv[2]
m = json.load(open(os.path.join(OUT, 'meta.json')))


def num(v):
    return 'Math.NaN' if v is None else repr(round(float(v), 6))


def arr(a):
    return '[' + ', '.join(num(v) for v in a) + ']'


def iarr(a):
    return '[' + ', '.join(str(int(v)) for v in a) + ']'


L = ['package toymaniak;', '', '// generated by toymaniak_data.py from the original SWF (do not edit)', 'class Data {']


def const(comment, name, typ, val, inline=False):
    if comment:
        L.append('\t// ' + comment)
    L.append('\tpublic static %svar %s:%s = %s;' % ('inline ' if inline else '', name, typ, val))


s = m['slots']
const('box: position and depth of its slots s0, s1, s2', 'SLOTS', 'Array<Array<Float>>',
      '[' + ', '.join(arr(s[k]) for k in ('s0', 's1', 's2')) + ']')
sl = m['slot']
assert sl['labels'] == {'fall': 2, 'empty': 17} and sl['frames'] == 23
# (an empty DoAction on frame 1: no stop there; ActionGotoFrame alone is gotoAndStop)
assert sl['actions'] == {'1': "[]", '16': "[('stop',)]", '23': "[('goto', 1)]"}, sl['actions']
const('slot (23 frames: stop on 16, "fall" = 2, "empty" = 17, gotoAndStop(1) on 23): y of the bar and of the toy '
      '(NaN: no toy) on each frame; their x', 'SLOT_BAR', 'Array<Float>', arr(sl['bar']))
const(None, 'SLOT_TOY', 'Array<Float>', arr(sl['toy']))
const(None, 'SLOT_BAR_X', 'Float', num(sl['barX']), True)
const(None, 'SLOT_TOY_X', 'Float', num(sl['toyX']), True)
h = m['slotHit']
const('hit area of a slot (shape 37): run-length rows (start, end, ...) at SLOT_HIT_RES samples per Flash pixel from '
      '(SLOT_HIT_X, SLOT_HIT_Y)', 'SLOT_HIT_X', 'Float', num(h['x0']), True)
const(None, 'SLOT_HIT_Y', 'Float', num(h['y0']), True)
const(None, 'SLOT_HIT_RES', 'Int', str(h['res']), True)
const(None, 'SLOT_HIT', 'Array<Array<Int>>', '[' + ', '.join(iarr(r) for r in h['rows']) + ']')
const('toy.but: its rectangle in the toy (xmin, xmax, ymin, ymax: the hit area of the toys of the rails)', 'BUT_RECT',
      'Array<Float>', arr(m['butRect']))
const('toy: on each of its 23 frames, the picture (index of the "toyN" anims; null: none) and its matrix (x, y, xscale, '
      'yscale)', 'TOY_FRAMES', 'Array<Array<Float>>',
      '[' + ', '.join('null' if f is None else arr(f) for f in m['toyFrames']) + ']')
const('texture pixels per Flash pixel of the "toyN" pictures (1: bitmaps at their native resolution)', 'TOY_RES',
      'Array<Float>', arr(m['toyRes']))
const('toy.getBounds(toy) on each frame (xmin, xmax, ymin, ymax: the invisible button included)', 'TOY_BOUNDS',
      'Array<Array<Float>>', '[' + ', '.join(arr(b) for b in m['toyBounds']) + ']')
f = m['front']
const('railFront: position of t0, t1, cruncher; the rectangle of the mask over the cruncher (xmin, xmax, ymin, ymax)',
      'FRONT_T0', 'Array<Float>', arr(f['t0']))
const(None, 'FRONT_T1', 'Array<Float>', arr(f['t1']))
const(None, 'FRONT_CRUNCHER', 'Array<Float>', arr(f['cruncher']))
const(None, 'FRONT_MASK', 'Array<Float>', arr(f['mask']))
li = m['lights']
for k in ('green', 'red'):
    assert li[k]['actions']['1'] == "[('stop',)]" and li[k]['actions']['2'].startswith('[') and "('goto', 3)" in li[k]['actions']['10']
const('railBack: panel.green and panel.red in the railBack (10 frames: stop on 1, compt = 3 on 2, '
      'if (compt-- > 0) gotoAndPlay(3) on 10)', 'GREEN', 'Array<Float>', arr([li['green']['x'], li['green']['y']]))
const(None, 'RED', 'Array<Float>', arr([li['red']['x'], li['red']['y']]))
d = m['digits']
const('panel.field (font Digital 15, left): advance of each digit, x of the text and its baseline in the railBack',
      'DIGIT_ADV', 'Array<Float>', arr(d['adv']))
const(None, 'DIGIT_X', 'Float', num(d['x']), True)
const(None, 'DIGIT_BASE', 'Float', num(d['base']), True)
L.append('}')
open(DEST, 'w').write('\n'.join(L) + '\n')
