"""Writes chakrebouddha/Data.hx from the asset pipeline output (meta.json).
usage: chakrebouddha_data.py <out dir of chakrebouddha_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def num(x):
    x = float(x)
    return repr(int(x)) + '.0' if x.is_integer() else repr(round(x, 5))


def arr(v):
    return '[' + ', '.join(num(x) for x in v) + ']'


d = meta['digits']
p = meta['points']
m = meta['mask']
lines = [
    'package chakrebouddha;',
    '',
    '// generated by chakrebouddha_data.py from the original SWF (do not edit)',
    'class Data {',
    '\t// mcLotus: for each of its 39 frames, the matrices (a, b, c, d, tx, ty) of the lotus bitmap at its 6 depths',
    '\tpublic static var LOTUS:Array<Array<Array<Float>>> = [',
] + ['\t\t[' + ', '.join(arr(x) for x in f) + '],' for f in meta['lotus']] + [
    '\t];',
    '\t// mcActive: resolutions of the ring pictures ring<r> (texture pixels per Flash pixel of the clip)',
    '\tpublic static var RING_RES:Array<Int> = [%s];' % ', '.join(str(r) for r in meta['ringRes']),
    '\t// mcMask: its rectangle (x0, x1, y0, y1) and the top of the picture maskedge, in the clip',
    '\tpublic static var MASK_RECT:Array<Float> = %s;' % arr(m['rect']),
    '\tpublic static inline var MASK_Y0 = %s;' % num(m['y0']),
    '\t// mcPoints.text (Ginko 25, centred): the digits of the anims digit (res DIGIT_RES) and digitbig (characters',
    '\t// DIGIT_BIG, res DIGIT_BIG_RES), their advances, the text area x0..x1 and the first baseline (Flash layout)',
    '\tpublic static var DIGIT_CHARS = "%s";' % d['chars'],
    '\tpublic static var DIGIT_BIG = "%s";' % d['big'],
    '\tpublic static inline var DIGIT_RES = %s;' % num(d['res']),
    '\tpublic static inline var DIGIT_BIG_RES = %s;' % num(d['bigRes']),
    '\tpublic static var DIGIT_ADV:Array<Float> = %s;' % arr(d['adv']),
    '\tpublic static inline var POINTS_X0 = %s;' % num(p['x0']),
    '\tpublic static inline var POINTS_X1 = %s;' % num(p['x1']),
    '\tpublic static inline var POINTS_BASE = %s;' % num(p['base']),
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
