"""Writes opalusfactory/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: opalusfactory_data.py <out dir of opalusfactory_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


def iarr(v):
    if isinstance(v, list):
        return '[' + ', '.join(iarr(x) for x in v) + ']'
    return str(int(v))


def fld(f):
    ls = ', '.join('{anim: "%s", color: 0x%06X, shadow: %s}' % (a, c, 'true' if k == 'shadow' else 'false') for a, c, k in f['layers'])
    return '{x: %r, w: %r, base: %r, layers: [%s]}' % (float(f['x']), float(f['w']), float(f['base']), ls)


hit = meta['hit']
cb = meta['caseBounds']
lines = [
    'package opalusfactory;',
    '',
    '// a layer of a text field: white digits (pivot on the pen position of the baseline) tinted; shadow: the drop shadow',
    '// of the clip holding the field (moved down by the game)',
    'typedef FieldLayer = {anim:String, color:Int, shadow:Bool};',
    '// a text field of the SWF: its text area (x, width) and first baseline in its clip, its layers from the bottom (the',
    '// glows of its filters, then the digits)',
    'typedef FieldDef = {x:Float, w:Float, base:Float, layers:Array<FieldLayer>};',
    '',
    '// generated by opalusfactory_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// nested clips the code reaches: order.smc (the hole), blockHole._count, points._p (pictures without timeline)',
    '\tpublic static inline var HOLE_CLIP = "%s";' % meta['holeClip'],
    '\tpublic static inline var COUNT_CLIP = "%s";' % meta['countClip'],
    '',
    '\t// mcDoor._top._height, mcDoor._bottom._height',
    '\tpublic static inline var DOOR_TOP_HEIGHT = %r;' % float(meta['doorTopHeight']),
    '\tpublic static inline var DOOR_BOTTOM_HEIGHT = %r;' % float(meta['doorBottomHeight']),
    '\t// the bounds of a case clip (xMin, xMax, yMin, yMax): MovieClip.hitTest(x, y) without shapeFlag',
    '\tpublic static var CASE_BOUNDS:Array<Float> = %s;' % arr(cb),
    '\t// the shape of a case (and its coin) as Flash tests the mouse on a button: rows of [x0, x1[ runs at HIT_Z px per',
    '\t// Flash pixel, row 0 / column 0 at (HIT_X, HIT_Y)',
    '\tpublic static inline var HIT_Z = %d;' % hit['z'],
    '\tpublic static inline var HIT_X = %r;' % float(hit['ox']),
    '\tpublic static inline var HIT_Y = %r;' % float(hit['oy']),
    '\tpublic static var HIT_ROWS:Array<Array<Array<Int>>> = %s;' % iarr(hit['rows']),
    '\t// _yscale of the frames of the focus overlay "caseRim"',
    '\tpublic static var RIM_SCALES:Array<Float> = %s;' % arr(meta['rimScales']),
    '',
    '\t// text fields: the hole of each colour (order.smc frame i + 1), blockHole._count, points._p',
    '\tpublic static var HOLE_FIELDS:Array<FieldDef> = [%s];' % ', '.join(fld(f) for f in meta['holeFields']),
    '\tpublic static var COUNT_FIELD:FieldDef = %s;' % fld(meta['countField']),
    '\tpublic static var P_FIELD:FieldDef = %s;' % fld(meta['pField']),
    '\t// advances of the digits of Trebuchet MS Bold 14 (holes, nuts) and 12 (points)',
    '\tpublic static var ADV14:Array<Float> = %s;' % arr(meta['dig14']),
    '\tpublic static var ADV12:Array<Float> = %s;' % arr(meta['dig12']),
    '\t// points: the distance of the drop shadow of _p on each frame (stage pixels, down)',
    '\tpublic static var P_SHADOW:Array<Float> = %s;' % arr(meta['pShadow']),
    '\t// wallUp\'s tapi (anim "tapi", blurred, drawn in overlay mode by the game): its picture in Flash pixels',
    '\tpublic static var TAPI:Array<Float> = %s;' % arr([meta['tapi'][k] for k in ('x', 'y', 'w', 'h')]),
    '\t// order: frames 1..ORDER_INTRO show the blurred hole of each colour (anim "orderIn<colour>")',
    '\tpublic static inline var ORDER_INTRO = %d;' % meta['orderIntro'],
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
