"""Writes aquasplash/Data.hx from the asset pipeline output (meta.json).
usage: aquasplash_data.py <out dir of aquasplash_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def num(x):
    if isinstance(x, bool):
        return 'true' if x else 'false'
    return repr(int(x)) if float(x).is_integer() else repr(float(x))


def arr(v):
    if v is None:
        return '[]'
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return num(v)


def mask(m):
    return '{y: %d, rows: "%s"}' % (m['y'], m['rows'])


def text(key):
    d = meta[key]
    return ('{chars: "%s", adv: %s, x0: %s, x1: %s, base: %s, lineH: %s, wrap: %s, align: "%s", anim: "%s", '
            'layers: %d, blurS: %s, m: %s}'
            % (d['chars'], arr([float(a) for a in d['adv']]), num(d['x0']), num(d['x1']), num(d['base']),
               num(d['lineH']), num(d['wrap']), d['align'], key, d['layers'], arr(d['blurS']),
               arr([float(v) for v in d['m']])))


sl = meta['slimes']
lines = [
    'package aquasplash;',
    '',
    '// generated by aquasplash_data.py from the original SWF (do not edit)',
    'class Data {',
    '\t// slime frames 1-4 (anims slime1..4): frames of their goute (it plays once and stops on the last one), then',
    '\t// for the goutes ending on blinking eyes the 3 pictures of the blink (eyeClose frames 2, 3, 4)',
    '\tpublic static var GOUTE_FRAMES:Array<Int> = %s;' % arr([s['n'] for s in sl]),
    '\tpublic static var GOUTE_BLINK:Array<Bool> = %s;' % arr([s['blink'] for s in sl]),
    '\t// bounds of each slime picture [xmin, xmax, ymin, ymax] (Flash getBounds: what Drop.onSlime\'s hitTest compares),',
    '\t// then frame 5 (the invisible square 125 alone), the drop (not rotated)',
    '\tpublic static var SLIME_BOUNDS:Array<Array<Array<Float>>> = [\n%s\n\t];' % ',\n'.join(
        '\t\t' + arr([[float(v) for v in b] for b in s['bounds']]) for s in sl),
    '\tpublic static var SLIME5_BOUNDS:Array<Float> = %s;' % arr([float(v) for v in meta['slime5']['bounds']]),
    '\tpublic static var DROP_BOUNDS:Array<Float> = %s;' % arr([float(v) for v in meta['dropBounds']]),
    '\t// hit areas of the slime buttons (the shapes of each picture, the invisible square included): first row (texture',
    '\t// pixels from the clip origin), then the rows of covered pixels, "start-end" runs (x from the clip origin)',
    '\tpublic static var SLIME_MASKS:Array<Array<HitMask>> = [\n%s\n\t];' % ',\n'.join(
        '\t\t[' + ', '.join(mask(m) for m in s['masks']) + ']' for s in sl),
    '\tpublic static var SLIME5_MASK:HitMask = %s;' % mask(meta['slime5']['mask']),
    '\t// _timeLeft (shape 9): width and height',
    '\tpublic static inline var TIME_LEFT_W = %s;' % num(meta['timeLeftW']),
    '\tpublic static inline var TIME_LEFT_H = %s;' % num(meta['timeLeftH']),
    '\t// nextLevel, frames 1-58: [gradient (d1), levelburn (d3), banner (d7)], each [x, y, alpha, grey multiplier, grey',
    '\t// offset(, blurred variant: -1 none)] or [] when absent',
    '\tpublic static var NEXT_LEVEL:Array<Array<Array<Float>>> = [\n%s\n\t];' % ',\n'.join(
        '\t\t' + arr(f) for f in meta['nextLevel']),
    '\t// blurred variants (anims nlBanner_B<i>, nlPlate_B<i>, glyphLevel_B<i>): kept at 1 / s of the horizontal resolution',
    '\tpublic static var BANNER_BLUR_S:Array<Int> = %s;' % arr(meta['bannerBlurS']),
    '\tpublic static var PLATE_BLUR_S:Array<Int> = %s;' % arr(meta['plateBlurS']),
    '\t// text fields: glyphs of the embedded fonts (anim + "_L<layer>", frame = index in chars, pivot on the pen point),',
    '\t// advances, text area x0..x1, first baseline and line height (field units), wordWrap, alignment, layers of the',
    '\t// field filters, matrix of the field in its clip [a, b, c, d, tx, ty]',
    '\tpublic static var TEXT_LEVEL:TextDef = %s;' % text('glyphLevel'),
    '\tpublic static var TEXT_SCORE:TextDef = %s;' % text('glyphScore'),
    '}',
    '',
    'typedef HitMask = {y:Int, rows:String};',
    '',
    'typedef TextDef = {chars:String, adv:Array<Float>, x0:Float, x1:Float, base:Float, lineH:Float, wrap:Bool,',
    '\talign:String, anim:String,',
    '\tlayers:Int, blurS:Array<Int>, m:Array<Float>};',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
