"""Writes cosmocrash/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: cosmocrash_data.py <out dir of cosmocrash_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')
var = json.dumps(meta['var340'], separators=(',', ':')).replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


def iarr(v):
    if isinstance(v, list):
        return '[' + ', '.join(iarr(x) for x in v) + ']'
    return str(int(v))


d = meta['digits']
la = meta['launch']
g = meta['ground']
lv = meta['level']
lines = [
    'package cosmocrash;',
    '',
    '// generated by cosmocrash_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '\tstatic var _var340:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// Folk.applySkin (Col.setColor(smc, colour, -340)) on the smc of "_hello" / "_face": clip -> {colour: variant}',
    '\tpublic static function var340():Dynamic {',
    '\t\tif (_var340 == null)',
    '\t\t\t_var340 = haxe.Json.parse(VAR340);',
    '\t\treturn _var340;',
    '\t}',
    '',
    '\t// bmpLevel (drawn from mt.Rand(0)): anim "ground", tiles of GROUND_TILE x (450 - GROUND_Y) from x = 0, y = GROUND_Y',
    '\tpublic static inline var GROUND_Y = %d;' % g['y0'],
    '\tpublic static inline var GROUND_TILE = %d;' % g['tile'],
    '\tpublic static inline var GROUND_TILES = %d;' % g['n'],
    '\t// the level the pictures were drawn for (the game checks its own genLevel against it in debug builds)',
    '\tpublic static var LEVEL_TOP:Array<Int> = %s;' % iarr(lv['top']),
    '\tpublic static var LEVEL_PLATS:Array<Array<Int>> = %s;' % iarr(lv['plats']),
    '\t// mcBg drawn into the 10 x 10 bitmap of the background (0xRRGGBB, rows)',
    '\tpublic static var BG:Array<Int> = %s;' % iarr(meta['bg']),
    '\t// mc._width of mcDecor on frame i + 1',
    '\tpublic static var DECOR_WIDTH:Array<Float> = %s;' % arr(meta['decorWidth']),
    '\t// skin.rampe.shuttle on frame 74 of the ramp (_x, _y, _rotation) and skin.rampe._yscale',
    '\tpublic static inline var LAUNCH_X = %r;' % float(la['x']),
    '\tpublic static inline var LAUNCH_Y = %r;' % float(la['y']),
    '\tpublic static inline var LAUNCH_ROT = %r;' % float(la['rot']),
    '\tpublic static inline var RAMPE_YSCALE = %r;' % float(la['rampeYScale']),
    '\t// canon.smc (_x, _y) in mcCanon',
    '\tpublic static var CANON_SMC:Array<Float> = %s;' % arr(meta['canonSmc']),
    '\t// smc (_x, _y) of partHero on frames 1..12',
    '\tpublic static var PART_HERO_SMC:Array<Array<Float>> = %s;' % arr(meta['partHeroSmc']),
    '\t// fxScore.smc text field (ProggySmallTT 18, centred): digits (anim "digits" at DIGITS_RES), advances, text area',
    '\t// and first baseline in smc',
    '\tpublic static var DIGITS_ADV:Array<Float> = %s;' % arr(d['adv']),
    '\tpublic static inline var DIGITS_X = %r;' % float(d['x']),
    '\tpublic static inline var DIGITS_W = %r;' % float(d['w']),
    '\tpublic static inline var DIGITS_BASE = %r;' % float(d['base']),
    '\tpublic static inline var DIGITS_RES = %r;' % float(d['res']),
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '\tstatic var VAR340 = "%s";' % var,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
