"""Writes resources/hx/games/hypercube/Data.hx from the meta.json of hypercube_assets.py.
usage: hypercube_data.py <out dir of hypercube_assets.py> <Data.hx>"""
import os, sys, json

OUT, DEST = sys.argv[1], sys.argv[2]
m = json.load(open(os.path.join(OUT, 'meta.json')))


def num(v):
    return repr(round(float(v), 6))


def arr(a):
    return '[' + ', '.join(num(v) for v in a) + ']'


L = ['package hypercube;', '', '// generated by hypercube_data.py from the original SWF (do not edit)', 'class Data {']


def const(comment, name, typ, val, inline=True):
    if comment:
        L.append('\t// ' + comment)
    L.append('\tpublic static %svar %s:%s = %s;' % ('inline ' if inline else '', name, typ, val))


r = m['ray']
const('bg.ray: position, _alpha (the stripes of the conveyor, 320 x 64, 1 texture pixel per Flash pixel)', 'RAY_X',
      'Float', num(r['x']))
const(None, 'RAY_Y', 'Float', num(r['y']))
const(None, 'RAY_ALPHA', 'Float', num(r['alpha']))
h = m['horloge']
const('bg.horloge: position, scale, _alpha; texture pixels per unit of its ha pictures (166 frames)', 'HORLOGE_X',
      'Float', num(h['x']))
const(None, 'HORLOGE_Y', 'Float', num(h['y']))
const(None, 'HORLOGE_SCALE', 'Float', num(h['scale']))
const(None, 'HORLOGE_ALPHA', 'Float', num(h['alpha']))
const(None, 'HA_RES', 'Float', num(h['res']))
const('hit area of a cube for each frame of its sub (xmin, xmax, ymin, ymax in the cube)', 'CUBE_HIT',
      'Array<Array<Float>>', '[' + ', '.join(arr(a) for a in m['cubeHit']) + ']', False)
c = m['cubLight']
const('cubLight in the cube (frames 4-6)', 'CUBLIGHT_X', 'Float', num(c['x']))
const(None, 'CUBLIGHT_Y', 'Float', num(c['y']))
const('butExt: hit area added to the cubes of the conveyor (alpha 0)', 'BUT_EXT', 'Array<Float>', arr(m['butExt']),
      False)
const('partQueue: _alpha of its line on each of its 21 frames (t = 0 on the last one)', 'QUEUE_ALPHA', 'Array<Float>',
      arr(m['queueAlpha']), False)
const('partRound: frames (removeMovieClip on the last one)', 'ROUND_FRAMES', 'Int', str(m['roundFrames']))
s = m['square']
const('scoreSquare: position of bg; scale (percent) above which bg uses its big picture (squareBgBig)', 'SQUARE_BG_X',
      'Float', num(s['bgx']))
const(None, 'SQUARE_BG_Y', 'Float', num(s['bgy']))
const(None, 'SQUARE_BIG', 'Float', num(s['big']))
d = m['digits']
const('score field of scoreSquare.sf (Arcade Classic 20, y scale baked in the "digit" pictures): advances, text area '
      '(x0, x1) and first baseline in sf; sf position', 'DIGIT_ADV', 'Array<Float>', arr(d['adv']), False)
const(None, 'DIGIT_X0', 'Float', num(d['x0']))
const(None, 'DIGIT_X1', 'Float', num(d['x1']))
const(None, 'DIGIT_BASE', 'Float', num(d['base']))
const(None, 'SF_X', 'Float', num(d['sfx']))
const(None, 'SF_Y', 'Float', num(d['sfy']))
const('mcScore: y of its score panel on frames 1-21 (frame 22 removes the clip)', 'SCORE_Y', 'Array<Float>',
      arr(m['scoreY']), False)
const('butEndGame: hit area of smc (shape 15, in butEndGame), _alpha of the text on its 21 frames (looping)', 'END_HIT',
      'Array<Float>', arr(m['endHit']), False)
const(None, 'END_TEXT_ALPHA', 'Array<Float>', arr(m['endTextAlpha']), False)
L.append('}')
open(DEST, 'w').write('\n'.join(L) + '\n')
