package pacifik;

// generated by pacifik_data.py from the original SWF (do not edit)
class Data {
	// heights of the frames of mcOnde (_height) and of mcDock
	public static var ONDE_HEIGHTS:Array<Float> = [84.0, 80.0, 107.0];
	public static inline var DOCK_HEIGHT = 107.0;
	// bounds (x0, x1, y0, y1) of the shapes, per frame: mcCanon depth 1 and depth 4, mcFire (smc), mcBall
	public static var CANON_BACK:Array<Array<Float>> = [[-10.1, 10.1, -10.1, 10.1], [-10.1, 10.1, -10.1, 10.1], [-10.1, 10.1, -10.1, 10.1]];
	public static var CANON_FRONT:Array<Array<Float>> = [[-10.9, 6.1, -17.85, 18.15], [-10.9, 6.1, -17.85, 18.15], [-10.9, 6.1, -17.85, 18.1]];
	public static var FIRE:Array<Array<Float>> = [[-0.1, 20.1, -3.1, 3.1], [-0.1, 20.1, -3.1, 3.1], [-0.1, 20.1, -3.1, 3.1]];
	public static var BALL:Array<Array<Float>> = [[-2.75, 2.75, -2.75, 2.75], [-2.6, 2.6, -2.6, 2.6], [-2.75, 2.75, -2.75, 2.75]];
	// mcCar per frame: bounds of the clip (every shape, the invisible markers too), positions of smc (mcHitShip),
	// r1 and r2 (mcReactor; null: not on this frame)
	public static var CAR_BOUNDS:Array<Array<Float>> = [[-7.0855, 7.3323, -0.1, 14.3855], [-11.2636, 11.3369, 0.8565, 21.3636], [-10.5096, 10.6362, 1.1, 21.1596], [-8.3161, 8.4592, 1.6557, 17.9161], [-9.169, 9.2053, 1.1297, 18.0053]];
	public static var CAR_SMC:Array<Array<Float>> = [[-0.15, 5.65], [-0.15, 14.35], [0.1, 16.6], [-0.2, 8.55], [-0.15, 13.35]];
	public static var CAR_R1:Array<Array<Float>> = [[0.2, 0.0], [-0.2, 8.6], [-4.3, 1.2], [0.05, 1.9], [-4.35, 3.05]];
	public static var CAR_R2:Array<Array<Float>> = [null, null, [4.1, 1.2], null, [4.05, 3.05]];
	// bounds of the shapes of mcHitShip and mcReactor
	public static var HIT_SHIP:Array<Float> = [-2.1, 2.1, -1.85, 2.35];
	public static var REACTOR:Array<Float> = [-2.1, 2.1, -0.1, 1.1];
	// particles: per frame, the segments (x1, y1, x2, y2) of the polyline, its colour and its stroke width
	public static var PARTS:Dynamic<Array<{segs:Array<Array<Float>>, color:Int, width:Float}>> = {
		mcBallPart: [{segs: [[-0.8, 0.0, 0.7, 0.0]], color: 0xFFFF66, width: 0.25}, {segs: [[-0.8, 0.0, 0.7, 0.0]], color: 0xFF66FF, width: 0.25}, {segs: [[-0.8, 0.0, 0.7, 0.0]], color: 0x33FFFF, width: 0.25}],
		mcCanonPart: [{segs: [[14.0, 0.0, 0.0, 0.0]], color: 0x00FF99, width: 0.25}, {segs: [[11.0, 0.0, 0.0, 0.0]], color: 0x00FF99, width: 0.25}, {segs: [[-10.0, 0.0, 1.0, 0.0], [1.0, 0.0, 1.0, -6.0]], color: 0x00FF99, width: 0.25}, {segs: [[-10.0, 0.0, 1.0, 0.0], [1.0, 0.0, 1.0, -6.0]], color: 0xFFFF66, width: 0.25}, {segs: [[-10.0, 0.0, 1.0, 0.0], [1.0, 0.0, 1.0, -6.0]], color: 0x33FFFF, width: 0.25}],
		mcLaserPart: [{segs: [[0.0, 0.0, 6.0, 0.0]], color: 0x000000, width: 0.25}],
		mcCarPart: [{segs: [[0.95, 0.05, 0.05, 0.05], [0.05, 0.05, 0.05, 1.1], [0.05, -1.0, 0.05, 0.05], [0.05, 0.05, -0.7, 0.05]], color: 0xCCFF33, width: 0.25}],
		mcSmoke: [{segs: [[0.0, -2.0, 0.0, -8.0]], color: 0xFDE851, width: 0.25}, {segs: [[0.0, -2.0, 0.0, -8.0]], color: 0xFE9583, width: 0.25}]
	};
	// texts of the score pictures (frames of the anim score)
	public static var SCORES:Array<String> = ["100", "200", "400", "800"];
}
