"""Writes resources/hx/games/pacifik/Data.hx from <out>/meta.json (pacifik_assets.py).
usage: pacifik_data.py <out dir> <Data.hx>
"""
import sys, json, os

meta = json.load(open(os.path.join(sys.argv[1], 'meta.json')))


def f(v):
    return repr(float(v))


def arr(a):
    return '[' + ', '.join(f(x) for x in a) + ']'


def arr2(a):
    return '[' + ', '.join(arr(x) for x in a) + ']'


L = []
L.append('package pacifik;')
L.append('')
L.append('// generated by pacifik_data.py from the original SWF (do not edit)')
L.append('class Data {')
L.append('\t// heights of the frames of mcOnde (_height) and of mcDock')
L.append('\tpublic static var ONDE_HEIGHTS:Array<Float> = %s;' % arr(meta['ondeHeights']))
L.append('\tpublic static inline var DOCK_HEIGHT = %s;' % f(meta['dockHeight']))
L.append('\t// bounds (x0, x1, y0, y1) of the shapes, per frame: mcCanon depth 1 and depth 4, mcFire (smc), mcBall')
L.append('\tpublic static var CANON_BACK:Array<Array<Float>> = %s;' % arr2(meta['canonBack']))
L.append('\tpublic static var CANON_FRONT:Array<Array<Float>> = %s;' % arr2(meta['canonFront']))
L.append('\tpublic static var FIRE:Array<Array<Float>> = %s;' % arr2(meta['fire']))
L.append('\tpublic static var BALL:Array<Array<Float>> = %s;' % arr2(meta['ball']))
L.append('\t// mcCar per frame: bounds of the clip (every shape, the invisible markers too), positions of smc (mcHitShip),')
L.append('\t// r1 and r2 (mcReactor; null: not on this frame)')
L.append('\tpublic static var CAR_BOUNDS:Array<Array<Float>> = %s;' % arr2([c['bounds'] for c in meta['car']]))
L.append('\tpublic static var CAR_SMC:Array<Array<Float>> = %s;' % arr2([c['smc'] for c in meta['car']]))
L.append('\tpublic static var CAR_R1:Array<Array<Float>> = [%s];'
         % ', '.join('null' if c['r1'] is None else arr(c['r1']) for c in meta['car']))
L.append('\tpublic static var CAR_R2:Array<Array<Float>> = [%s];'
         % ', '.join('null' if c['r2'] is None else arr(c['r2']) for c in meta['car']))
L.append('\t// bounds of the shapes of mcHitShip and mcReactor')
L.append('\tpublic static var HIT_SHIP:Array<Float> = %s;' % arr(meta['hitShip']))
L.append('\tpublic static var REACTOR:Array<Float> = %s;' % arr(meta['reactor']))
L.append('\t// particles: per frame, the segments (x1, y1, x2, y2) of the polyline, its colour and its stroke width')
L.append('\tpublic static var PARTS:Dynamic<Array<{segs:Array<Array<Float>>, color:Int, width:Float}>> = {')
items = []
for name, frames in meta['parts'].items():
    fr = ', '.join('{segs: %s, color: 0x%06X, width: %s}' % (arr2(p['segs']), p['color'], f(p['width'])) for p in frames)
    items.append('\t\t%s: [%s]' % (name, fr))
L.append(',\n'.join(items))
L.append('\t};')
L.append('\t// texts of the score pictures (frames of the anim score)')
L.append('\tpublic static var SCORES:Array<String> = [%s];' % ', '.join('"%s"' % s for s in meta['scores']))
L.append('}')
open(sys.argv[2], 'w').write('\n'.join(L) + '\n')
