"""Writes digestomax/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: digestomax_data.py <out dir of digestomax_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


d = meta['digits']
t = meta['timer']
lv = meta['levels']
lines = [
    'package digestomax;',
    '',
    '// generated by digestomax_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// anim "tile": mcTile frame 2 (frame 1), mcTile frame 1 with its smc on frame i (frame i + 1)',
    '\tpublic static inline var TILE_FRAMES = %d;' % meta['tileFrames'],
    '\t// mcTimer: x of its smc\'s band (sprite 24) on each frame of the smc, its width, the mask rectangle (smc.smc at',
    '\t// _xscale 100), the smc\'s _yscale, and the glow of the smc (blurX, blurY, strength, colour through its colour matrix)',
    '\tpublic static var TIMER_BAND_TX:Array<Float> = %s;' % arr(t['bandTx']),
    '\tpublic static inline var TIMER_BAND_X = %r;' % float(t['bandX']),
    '\tpublic static inline var TIMER_BAND_W = %r;' % float(t['bandW']),
    '\tpublic static inline var TIMER_MASK_W = %r;' % float(t['maskW']),
    '\tpublic static inline var TIMER_MASK_H = %r;' % float(t['maskH']),
    '\tpublic static inline var TIMER_SMC_YSCALE = %r;' % float(t['yscale']),
    '\tpublic static var TIMER_GLOW:Array<Float> = %s;' % arr(t['glow'][:3]),
    '\tpublic static inline var TIMER_GLOW_COLOR = 0x%06X;' % t['glow'][3],
    '\t// anim "levelText": mcLevel with "x" + n for n = LEVEL_MIN + frame - 1',
    '\tpublic static inline var LEVEL_MIN = %d;' % lv[0],
    '\tpublic static inline var LEVEL_MAX = %d;' % lv[-1],
    '\t// partScore.smc text field (Impact, centred): digits (anim "digits" at DIGITS_RES), advances, text area and',
    '\t// first baseline in smc, resolution of the smc picture',
    '\tpublic static var DIGITS_ADV:Array<Float> = %s;' % arr(d['adv']),
    '\tpublic static inline var DIGITS_X = %r;' % float(d['x']),
    '\tpublic static inline var DIGITS_W = %r;' % float(d['w']),
    '\tpublic static inline var DIGITS_BASE = %r;' % float(d['base']),
    '\tpublic static inline var DIGITS_RES = %r;' % float(d['res']),
    '\tpublic static inline var DIGITS_SMC_RES = %r;' % float(d['smcRes']),
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
