package toymaniak;

// generated by toymaniak_data.py from the original SWF (do not edit)
class Data {
	// box: position and depth of its slots s0, s1, s2
	public static var SLOTS:Array<Array<Float>> = [[-46.0, -27.4, 26.0], [0.0, -27.4, 2.0], [46.0, -27.4, 14.0]];
	// slot (23 frames: stop on 16, "fall" = 2, "empty" = 17, gotoAndStop(1) on 23): y of the bar and of the toy (NaN: no toy) on each frame; their x
	public static var SLOT_BAR:Array<Float> = [9.05, 9.05, 9.05, 9.05, 9.05, 9.05, 11.9, 14.05, 15.45, 14.2, 12.35, 9.85, 11.1, 12.35, 12.1, 11.85, 11.85, 10.5, 9.1, 7.75, 8.2, 8.6, 9.05];
	public static var SLOT_TOY:Array<Float> = [Math.NaN, -25.25, -16.75, -8.25, 0.25, 8.75, 11.6, 13.75, 15.15, 13.9, 12.05, 9.55, 10.8, 12.05, 11.8, 11.55, Math.NaN, Math.NaN, Math.NaN, Math.NaN, Math.NaN, Math.NaN, Math.NaN];
	public static inline var SLOT_BAR_X:Float = -0.1;
	public static inline var SLOT_TOY_X:Float = -0.45;
	// hit area of a slot (shape 37): run-length rows (start, end, ...) at SLOT_HIT_RES samples per Flash pixel from (SLOT_HIT_X, SLOT_HIT_Y)
	public static inline var SLOT_HIT_X:Float = -21.5;
	public static inline var SLOT_HIT_Y:Float = -21.5;
	public static inline var SLOT_HIT_RES:Int = 4;
	public static var SLOT_HIT:Array<Array<Int>> = [[16, 156], [12, 160], [10, 162], [9, 163], [7, 165], [6, 166], [5, 167], [4, 168], [4, 168], [3, 169], [2, 170], [2, 170], [1, 171], [1, 171], [1, 171], [0, 171], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 172], [0, 171], [1, 171], [1, 171], [1, 171], [2, 170], [2, 170], [3, 169], [4, 168], [4, 167], [5, 166], [6, 165], [7, 164], [9, 163], [10, 162], [12, 160], [16, 156]];
	// toy.but: its rectangle in the toy (xmin, xmax, ymin, ymax: the hit area of the toys of the rails)
	public static var BUT_RECT:Array<Float> = [-25.0, 25.0, -52.25, 7.75];
	// toy: on each of its 23 frames, the picture (index of the "toyN" anims; null: none) and its matrix (x, y, xscale, yscale)
	public static var TOY_FRAMES:Array<Array<Float>> = [[0.0, 0.1, -15.6, 1.0, 1.0], [1.0, -0.35, -14.6, 1.0, 1.0], [2.0, 0.0, 0.0, 1.0, 1.0], [3.0, 0.0, 0.0, 1.001694, 1.0], [4.0, -0.3, -8.3, 1.0, 1.0], [5.0, 0.15, -14.95, 1.0, 1.0], [6.0, 0.05, -15.45, 1.0, 1.0], [7.0, 0.15, -14.95, 1.0, 1.0], [8.0, 0.15, -14.95, 1.0, 1.0], [9.0, 0.0, 0.0, 1.0, 1.0], [10.0, 0.0, 0.0, 0.99707, 1.0], [10.0, 0.0, 0.0, 0.99707, 1.0], [10.0, 0.0, 0.0, 0.99707, 1.0], [10.0, 0.0, 0.0, 0.99707, 1.0], [10.0, 0.0, 0.0, 0.99707, 1.0], [10.0, 0.0, 0.0, 0.99707, 1.0], null, null, null, null, null, null, null];
	// texture pixels per Flash pixel of the "toyN" pictures (1: bitmaps at their native resolution)
	public static var TOY_RES:Array<Float> = [1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0];
	// toy.getBounds(toy) on each frame (xmin, xmax, ymin, ymax: the invisible button included)
	public static var TOY_BOUNDS:Array<Array<Float>> = [[-25.0, 25.0, -52.25, 7.75], [-25.85, 27.15, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-31.9, 31.5, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75], [-25.0, 25.0, -52.25, 7.75]];
	// railFront: position of t0, t1, cruncher; the rectangle of the mask over the cruncher (xmin, xmax, ymin, ymax)
	public static var FRONT_T0:Array<Float> = [-300.0, 0.05];
	public static var FRONT_T1:Array<Float> = [-300.0, 10.0];
	public static var FRONT_CRUNCHER:Array<Float> = [-263.0, -48.8];
	public static var FRONT_MASK:Array<Float> = [-280.15, -247.05, -31.75, 4.3];
	// railBack: panel.green and panel.red in the railBack (10 frames: stop on 1, compt = 3 on 2, if (compt-- > 0) gotoAndPlay(3) on 10)
	public static var GREEN:Array<Float> = [-196.3, -48.7];
	public static var RED:Array<Float> = [-196.3, -42.0];
	// panel.field (font Digital 15, left): advance of each digit, x of the text and its baseline in the railBack
	public static var DIGIT_ADV:Array<Float> = [8.6279, 8.6279, 8.6279, 8.6279, 8.6279, 8.6279, 8.6279, 8.6279, 8.6279, 8.6279];
	public static inline var DIGIT_X:Float = -227.9;
	public static inline var DIGIT_BASE:Float = -39.837891;
}
