"""Writes klinkersurprise/Data.hx from the asset pipeline output (meta.json).
usage: klinkersurprise_data.py <out dir of klinkersurprise_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def num(x):
    x = float(x)
    return repr(int(x)) + '.0' if x.is_integer() else repr(round(x, 4))


def arr(v):
    return '[' + ', '.join(num(x) for x in v) + ']'


f = meta['field']
lines = [
    'package klinkersurprise;',
    '',
    '// generated by klinkersurprise_data.py from the original SWF (do not edit)',
    'class Data {',
    '\t// mcInter: placement of the time bars b0 and b1 (x, y, xscale, yscale)',
    '\tpublic static var B0:Array<Float> = %s;' % arr(meta['b0']),
    '\tpublic static var B1:Array<Float> = %s;' % arr(meta['b1']),
    '\t// mcInter.field (Larabiefont 20, centred): characters of the anim glyph, their advances, text area x0..x1,',
    '\t// first baseline (Flash layout: 2 px gutter, baseline at the ascent)',
    '\tpublic static var FIELD_CHARS = "%s";' % f['chars'].replace('"', '\\"'),
    '\tpublic static var FIELD_ADV:Array<Float> = %s;' % arr(f['adv']),
    '\tpublic static inline var FIELD_X0 = %s;' % num(f['x0']),
    '\tpublic static inline var FIELD_X1 = %s;' % num(f['x1']),
    '\tpublic static inline var FIELD_BASE = %s;' % num(f['base']),
    '\t// mcLight pictures light0..: texture pixels per Flash pixel of the clip',
    '\tpublic static var LIGHT_RES:Array<Float> = %s;' % arr(meta['lightRes']),
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
