"""Writes cyclopean/Data.hx from the asset pipeline output (meta.json).
usage: cyclopean_data.py <out dir of cyclopean_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def num(x):
    if isinstance(x, int) or float(x).is_integer():
        return repr(float(x))
    return repr(round(float(x), 10))


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return num(v)


def ints(v):
    return '[' + ', '.join(str(int(x)) for x in v) + ']'


def deltas(c):
    # contour [x0, y0, x1, y1...] in 1/64 px -> first point then differences (a shorter JSON)
    out = [c[0], c[1]]
    for i in range(2, len(c), 2):
        out += [c[i] - c[i - 2], c[i + 1] - c[i - 1]]
    return out


def piece(p):
    return {'r': p['rect'], 'p': [[deltas(c) for c in path] for path in p['polys']],
            'a': p['anchors'], 'o': p['others']}


pieces = {'first': piece(meta['first']), 'bases': [piece(p) for p in meta['bases']],
          'anchor': {'r': meta['anchorShape']['rect'], 'p': [[deltas(c) for c in path] for path in meta['anchorShape']['polys']]}}
js = json.dumps(pieces, separators=(',', ':'))
ld = meta['loader']
it = meta['inter']
lines = [
    'package cyclopean;',
    '',
    '// generated by cyclopean_data.py from the original SWF (do not edit)',
    'class Data {',
    '\t// the pieces Game.genLevel carves the level with (mcFirst, then the 21 frames of mcBase) and the shape of their',
    '\t// $a anchors (sprite 121), parsed by Level: r: bounds of the shape (xmin, xmax, ymin, ymax); p: its fill paths',
    '\t// (each filled even-odd, united), contours in 1/64 px, first point then differences; a: the anchors Std.getVar',
    '\t// finds ($a0, $a1... until one is missing): x, y, _rotation, matrix a b c d; o: the other anchors (children too)',
    '\tpublic static var PIECES = \'%s\';' % js,
    '\t// mcLoader timeline, per frame: _rotation of the two quarter discs (depth 4, by quarters: the mask of depth 6),',
    '\t// cover (anim loaderCover frame, 0: none)',
    '\tpublic static var LOADER_Q4:Array<Float> = %s;' % arr(ld['q4']),
    '\tpublic static var LOADER_Q6:Array<Float> = %s;' % arr(ld['q6']),
    '\tpublic static var LOADER_COVER:Array<Int> = %s;' % ints(ld['cover']),
    '\t// matrices (a, b, c, d, tx, ty) of children placed by the timelines',
    '\tpublic static var LOADER_PIOU:Array<Float> = %s;' % arr(ld['piou']),
    '\tpublic static var LOADER_WH:Array<Float> = %s;' % arr(ld['wh']),
    '\tpublic static var INTER_BAR:Array<Float> = %s;' % arr(it['bar']),
    '\tpublic static var INTER_CAP:Array<Float> = %s;' % arr(it['cap']),
    '\tpublic static var INTER_BARUP:Array<Float> = %s;' % arr(it['barUp']),
    '\t// mcInter.bar (the mask of the gauge): its rectangle (0, -H, W, H), _height at _yscale 100',
    '\tpublic static inline var INTER_BAR_W = %s;' % num(it['barW']),
    '\tpublic static inline var INTER_BAR_H = %s;' % num(it['barH']),
    '\tpublic static var ELEM_LIGHT:Array<Float> = %s;' % arr(meta['elemLight']),
    '\tpublic static var ELEM_SMOKE:Array<Float> = %s;' % arr(meta['elemSmoke']),
    '\tpublic static var FLAMB_LIGHT:Array<Float> = %s;' % arr(meta['flambLight']),
    '}',
    '',
]
open(DST, 'w').write('\n'.join(lines))
print('Data.hx: pieces %d bytes' % len(js))
