"""Writes linea/Data.hx from the asset pipeline output (meta.json).
usage: linea_data.py <out dir of linea_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def arr(v):
    return '[' + ', '.join(repr(x) for x in v) + ']'


stars = meta['stars']
lines = [
    'package linea;',
    '',
    '// generated by linea_data.py from the original SWF (do not edit)',
    'class Data {',
    '\t// _width / _height of mcSquare (every frame) and mcBonus',
    '\tpublic static inline var SQUARE_W = %r;' % meta['squareSize'][0],
    '\tpublic static inline var SQUARE_H = %r;' % meta['squareSize'][4],
    '\tpublic static inline var BONUS_W = %r;' % meta['bonusSize'][0],
    '\tpublic static inline var BONUS_H = %r;' % meta['bonusSize'][1],
    '\t// _width / _height of mcAddline for each frame of its nested mcAniglow (the ring grows: twips)',
    '\tpublic static var ADDLINE_W:Array<Float> = %s;' % arr(meta['addlineW']),
    '\tpublic static var ADDLINE_H:Array<Float> = %s;' % arr(meta['addlineH']),
    '\t// mcBonus: its mcSoloBonus children in depth order: name, x, y',
    '\tpublic static var STARS_NAME = %s;' % ('[' + ', '.join('"%s"' % s[0] for s in stars) + ']'),
    '\tpublic static var STARS_X:Array<Float> = %s;' % arr([float(s[1]) for s in stars]),
    '\tpublic static var STARS_Y:Array<Float> = %s;' % arr([float(s[2]) for s in stars]),
    '\t// mcBack (bitmap at its native resolution)',
    '\tpublic static inline var BACK_W = %r;' % meta['backSize'][0],
    '\tpublic static inline var BACK_H = %r;' % meta['backSize'][1],
    '\t// colours baked in the bonus stars and their particles (anims "star" / "bpart" + RRGGBB)',
    '\tpublic static var COLORS:Array<Int> = %s;' % ('[' + ', '.join('0x%06X' % c for c in meta['colors']) + ']'),
    '\t// values of the text fields rendered from the SWF (frame n = value n)',
    '\tpublic static inline var DFACTOR_MAX = %d;' % meta['dfactorMax'],
    '\tpublic static inline var LINE_SCORE_MAX = %d;' % meta['lineScoreMax'],
    '\tpublic static inline var MULT_MAX = %d;' % meta['multMax'],
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
