package electrolink;

// generated by electrolink_data.py from the original SWF (do not edit)
class Data {
	// colours of the 80 frames of the green / blue pulse (color clip, frames 2 and 3: morph shapes)
	public static var PULSE_GREEN:Array<Int> = [0x87CC33, 0x8ACD37, 0x8CCF3B, 0x8FD03F, 0x91D143, 0x94D247, 0x96D44B, 0x99D54F, 0x9CD653, 0x9ED857, 0xA1D95B, 0xA3DA5F, 0xA6DB63, 0xA8DD67, 0xABDE6A, 0xADDF6E, 0xB0E172, 0xB3E276, 0xB5E37A, 0xB8E47E, 0xBAE682, 0xBDE786, 0xBFE88A, 0xC2E98E, 0xC5EB92, 0xC7EC96, 0xCAED9A, 0xCCEF9E, 0xCFF0A2, 0xD1F1A6, 0xD4F2AA, 0xD6F4AE, 0xD9F5B2, 0xDCF6B6, 0xDEF8BA, 0xE1F9BE, 0xE3FAC2, 0xE6FBC6, 0xE8FDCA, 0xEBFECD, 0xE9FDC9, 0xE6FBC5, 0xE4FAC1, 0xE1F9BE, 0xDEF8BA, 0xDCF7B6, 0xD9F5B2, 0xD7F4AE, 0xD4F3AA, 0xD2F1A7, 0xD0F0A3, 0xCDEF9F, 0xCAEE9B, 0xC8EC97, 0xC5EB93, 0xC3EA90, 0xC0E98C, 0xBEE788, 0xBBE684, 0xB9E580, 0xB6E47C, 0xB4E279, 0xB1E175, 0xAFE071, 0xACDF6D, 0xAADD69, 0xA7DC65, 0xA5DB62, 0xA2DA5E, 0xA0D85A, 0x9DD756, 0x9BD652, 0x98D54E, 0x96D34B, 0x93D247, 0x91D143, 0x8ED03F, 0x8CCE3B, 0x89CD37, 0x87CC33];
	public static var PULSE_BLUE:Array<Int> = [0x008DCC, 0x058FCD, 0x0A92CF, 0x0E94D0, 0x1397D1, 0x1899D2, 0x1D9BD4, 0x229ED5, 0x27A0D6, 0x2BA3D8, 0x30A5D9, 0x35A8DA, 0x3AAADC, 0x3FACDD, 0x43AFDE, 0x48B1DF, 0x4DB4E1, 0x52B6E2, 0x57B8E3, 0x5CBBE5, 0x60BDE6, 0x65C0E7, 0x6AC2E8, 0x6FC4EA, 0x74C7EB, 0x79C9EC, 0x7DCCEE, 0x82CEEF, 0x87D0F0, 0x8CD3F2, 0x91D5F3, 0x95D8F4, 0x9ADAF5, 0x9FDDF7, 0xA4DFF8, 0xA9E1F9, 0xAEE4FB, 0xB2E6FC, 0xB7E9FD, 0xBCEBFE, 0xB7E9FD, 0xB3E6FC, 0xAEE4FA, 0xA9E2F9, 0xA4DFF8, 0xA0DDF7, 0x9BDBF5, 0x96D8F4, 0x92D6F3, 0x8DD3F2, 0x88D1F0, 0x84CFEF, 0x7FCCEE, 0x7ACAED, 0x75C8EB, 0x71C5EA, 0x6CC3E9, 0x67C1E8, 0x63BEE6, 0x5EBCE5, 0x59BAE4, 0x55B7E3, 0x50B5E2, 0x4BB3E0, 0x46B0DF, 0x42AEDE, 0x3DACDD, 0x38A9DB, 0x34A7DA, 0x2FA4D9, 0x2AA2D8, 0x26A0D6, 0x219DD5, 0x1C9BD4, 0x1799D3, 0x1396D1, 0x0E94D0, 0x0992CF, 0x058FCE, 0x008DCC];
	// tile hover glow pictures "hover<i>": rotation (degrees, mod 90) and scale of the tile they were computed for
	public static var HOVER_ROT:Array<Float> = [0.0, 0.0, 43.2, 86.4];
	public static var HOVER_SCALE:Array<Float> = [1.0, 1.2, 1.2, 1.2];
	// hit area of the tile buttons (shape 8: xmin, xmax, ymin, ymax)
	public static var TILE_HIT:Array<Float> = [-12.5, 12.5, -12.5, 12.5];
	// texture pixels per unit of the goal pictures (the goal is drawn at 70 %)
	public static inline var GOAL_RES = 1.4;
	// timeLeft: _width / _height at 100 %
	public static inline var TIME_LEFT_W = 200.0;
	public static inline var TIME_LEFT_H = 9.0;
	// part1 pictures "part<sy>": vertical scales (percent) baked in the textures
	public static var PART_SCALES:Array<Int> = [20, 30, 40, 50];
	// mcBg sparks: anim "spark<i>" (2 pictures per frame: frame of the path, frame of part1), frames of the path,
	// odds of the controller (random(n) + base == base + 1 every frame)
	public static var SPARK_FRAMES:Array<Int> = [60, 30, 30, 100];
	public static var SPARK_ODDS:Array<Int> = [200, 100, 100, 100];
	// scoring timeline: _t x, alpha and BlurFilter blurX for each of its 27 frames (stop() on the last one)
	public static var SCORING_X:Array<Float> = [0.0, -74.95, -149.85, -224.8, -225.5, -226.15, -226.85, -227.55, -228.2, -228.9, -229.6, -230.25, -230.95, -231.65, -232.35, -233.0, -233.7, -234.4, -235.05, -235.75, -236.45, -237.1, -237.8, -178.35, -118.9, -59.45, 0.0];
	public static var SCORING_ALPHA:Array<Float> = [0.0, 0.332031, 0.667969, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.75, 0.5, 0.25, 0.0];
	public static var SCORING_BLUR:Array<Float> = [200.0, 133.3344, 66.6656, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 25.0, 50.0, 75.0, 100.0];
	// TexasLED glyphs (anim "glyph", in this order): advances and ascent at the size of the fields
	public static inline var GLYPHS = "0123456789x";
	public static var GLYPH_ADV:Array<Float> = [23.125, 17.5391, 22.5391, 22.7344, 22.6953, 22.9688, 22.3047, 21.9141, 22.9688, 22.8516, 22.6172];
	public static inline var GLYPH_ASCENT = 31.0547;
	// text fields of _t: rectangle (x, y, width), right aligned or not, colour
	public static var FIELD_PTS = {x: -34.35, y: -15.6, w: 139.45, right: true, color: 0x174C68};
	public static var FIELD_MULT = {x: 152.7, y: -15.6, w: 77.25, right: false, color: 0x174C68};
	// filters of both fields: GlowFilter then DropShadowFilter (distance 0)
	public static var FIELD_GLOW = {blur: 2.0, strength: 10.0, passes: 2, color: 0xFFFFFF};
	public static var FIELD_SHADOW = {blur: 10.0, strength: 1.3984375, passes: 2, color: 0x3CD6F0};
}
