"""Writes ktrain/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: ktrain_data.py <out dir of ktrain_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))


def js(v):
    s = json.dumps(v, separators=(',', ':'))
    assert '\\' not in s
    return s.replace('"', '\\"')


def arr(v):
    return '[' + ', '.join(repr(float(x)) for x in v) + ']'


lines = [
    'package ktrain;',
    '',
    '// generated by ktrain_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '\tstatic var _bounds:Dynamic = null;',
    '\tstatic var _sub:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// getBounds of a clip on each frame, in its own coordinates (Flash pixels): clip -> [[xMin, yMin, xMax, yMax] or null]',
    '\tpublic static function bounds():Dynamic {',
    '\t\tif (_bounds == null)',
    '\t\t\t_bounds = haxe.Json.parse(BOUNDS);',
    '\t\treturn _bounds;',
    '\t}',
    '',
    '\t// getBounds of the named children (hit1, hit2, smc) in the coordinates of their clip, on each frame of the clip',
    '\t// (null: no such child on that frame): clip -> {name -> [[xMin, yMin, xMax, yMax] or null]}',
    '\tpublic static function sub():Dynamic {',
    '\t\tif (_sub == null)',
    '\t\t\t_sub = haxe.Json.parse(SUB);',
    '\t\treturn _sub;',
    '\t}',
    '',
    '\t// the frames of mcBg: the ground bitmap and whether it is flipped vertically',
    '\tpublic static var BG_FRAMES:Array<String> = [%s];' % ', '.join('"%s"' % b for b, _ in meta['bgFrames']),
    '\tpublic static var BG_FLIP:Array<Bool> = [%s];' % ', '.join('true' if f else 'false' for _, f in meta['bgFrames']),
    '\t// children of mcLevier the code reads: p, c (and f, moved by the code) (_x, _y)',
    '\tpublic static var LEV_P:Array<Float> = %s;' % arr(meta['lev_p']),
    '\tpublic static var LEV_C:Array<Float> = %s;' % arr(meta['lev_c']),
    '\tpublic static var LEV_F:Array<Float> = %s;' % arr(meta['lev_f']),
    '',
    '\tstatic var CLIPS = "%s";' % js(clips),
    '\tstatic var BOUNDS = "%s";' % js(meta['bounds']),
    '\tstatic var SUB = "%s";' % js(meta['sub']),
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
