"""Writes punchin/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: punchin_data.py <out dir of punchin_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def num(v):
    return repr(float(v))


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return num(v)


def txt(t):
    return '{anim: "%s", chars: "%s", adv: %s, x: %s, w: %s, base: %s, center: %s}' % (
        t['anim'], t['chars'], arr(t['adv']), num(t['x']), num(t['w']), num(t['base']), 'true' if t['center'] else 'false')


g, m = meta['stGauge'], meta['stMask']
tf = meta['textFrames']
lines = [
    'package punchin;',
    '',
    'import punchin.Txt.TxtDef;',
    '',
    '// generated by punchin_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// mcBg._width (the bounds of its shapes, in twips)',
    '\tpublic static inline var BG_WIDTH = %s;' % num(meta['bgWidth']),
    '\t// mcStamina: the gauge picture (anim "stGauge": its left and width), the mask rectangle at _xscale 100',
    '\tpublic static inline var ST_GAUGE_X = %s;' % num(g['x']),
    '\tpublic static inline var ST_GAUGE_W = %s;' % num(g['w']),
    '\tpublic static inline var ST_MASK_X = %s;' % num(m['x']),
    '\tpublic static inline var ST_MASK_W = %s;' % num(m['w']),
    '\t// text fields: mcChrono.label (device font Verdana Bold Italic) and mcText.sub.label (embedded Verdana Bold',
    '\t// Italic), and their colours',
    '\tpublic static var CHRONO_FIELD:TxtDef = %s;' % txt(meta['chronoField']),
    '\tpublic static inline var CHRONO_COLOR = 0x%06X;' % meta['chronoField']['color'],
    '\tpublic static var MSG_FIELD:TxtDef = %s;' % txt(meta['msgField']),
    '\tpublic static inline var MSG_COLOR = 0x%06X;' % meta['msgField']['color'],
    '\t// mcText: `sub` on each frame (x, y, scale, colour multiplier, added red, green, blue; null: removed), labels',
    '\tpublic static var TEXT_FRAMES:Array<Array<Float>> = [%s];' % ', '.join(
        'null' if r is None else arr([r[0], r[1], r[2], r[3]] + r[4]) for r in tf),
    '\t// its glow on each frame (blurX, blurY in stage pixels, strength, colour; null: none)',
    '\tpublic static var TEXT_GLOWS:Array<Array<Float>> = [%s];' % ', '.join(
        'null' if g is None else arr(g) for g in meta['textGlows']),
    '\tpublic static inline var TEXT_STOP = 9;',
    '\tpublic static inline var TEXT_END = %d;' % meta['textLabels']['end'],
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
