"""Writes judocommando/Data.hx from the asset pipeline output (clips.json, meta.json) and the levels of the original
(src/Levels.data, a resource of game.swf: the 13 levels encoded by mt.PersistCodec, decoded by Game at start).
usage: judocommando_data.py <out dir of judocommando_assets.py> <Levels.data> <Data.hx>"""
import sys, json, os, re

OUT, LEVELS, DST = sys.argv[1], sys.argv[2], sys.argv[3]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))
levels = open(LEVELS).read().strip()
assert re.fullmatch(r'[0-9A-Za-z%]+', levels), 'Levels.data: unexpected characters'

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')

lines = [
    'package judocommando;',
    '',
    '// generated by judocommando_data.py from the original SWF and Levels.data (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// mcBg drawn by Game.initBg and cut into bands of 15 px: the colour of each band (its pixel at x = 0)',
    '\tpublic static var SKY:Array<Int> = [%s];' % ', '.join(meta['sky']),
    '\t// frames of the smc of mcTiles, of the brick and of the plank of mcSquare',
    '\tpublic static inline var N_TILES = %d;' % meta['nTiles'],
    '\tpublic static inline var N_BRICK = %d;' % meta['nBrick'],
    '\tpublic static inline var N_PLANK = %d;' % meta['nPlank'],
    '',
    '\t// Levels.data of the original (haxe.Resource "Levels.data")',
    '\tpublic static var LEVELS_ENCRYPTED = "%s";' % levels,
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
