"""Phagocytoz: <out>/data.json (phagocytoz_assets.py) -> resources/hx/games/phagocytoz/Data.hx
usage: phagocytoz_data.py <out dir> <Data.hx>"""
import json, sys

out_dir, dest = sys.argv[1], sys.argv[2]
d = json.load(open(out_dir + '/data.json'))
raw = json.dumps(d, separators=(',', ':'), sort_keys=True)
assert "'" not in raw and '\\' not in raw.replace('\\"', '')
src = '''package phagocytoz;

// GENERATED by .opencode/skills/flash-port/scripts/examples/phagocytoz/phagocytoz_data.py from gfx.swf
// (phagocytoz_assets.py): do not edit, rebuild with rebuild_assets.sh.
//
// J.symbols[sid]: {frames: [[entries]], idx: [frame -> index in frames], cls, scripts: {frame: [ops]}}, an entry
//   being [kind ("M" clip / "L" leaf / "F" text field), ref, key, a, b, c, d, tx, ty, cx index, name index,
//   clipDepth, fx index]; a script op: "s" stop, ["r", lo, hi] gotoAndPlay(lo + random(hi - lo + 1)), ["g", f]
// J.leaves[name]: {res, ox, oy, w, h, b: bounds [x0, x1, y0, y1], lods: [[res, picture]], solid: colour}
// J.edits[id]: {b, align, letterSpacing, chars, adv, ascent, glyphs: [{res, anim}]}, J.cx / J.names / J.fx: tables
class Data {
	static var j:Dynamic = null;

	public static function get():Dynamic {
		if (j == null)
			j = haxe.Json.parse(RAW);
		return j;
	}

	static inline var RAW = '%s';
}
''' % raw
open(dest, 'w').write(src)
print('Data.hx', len(src))
