"""Writes razor/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: razor_data.py <out dir of razor_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


c = meta['comment']
lines = [
    'package razor;',
    '',
    '// generated by razor_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// mcCommentAnim (Comment): the texts of fxComment (anims "comment0".."comment4", white, at COMMENT_RES: 2 px per',
    '\t// stage pixel at the scale the code gives them), their textWidth in the field, the scale of sprite 4 in sprite 6;',
    '\t// sprite 4: the red copy (colour, alpha) and the knockout glow of the other copy (blurX, blurY, strength, colour)',
    '\tpublic static var COMMENT_TEXTS:Array<String> = [%s];' % ', '.join('"%s"' % t for t in c['texts']),
    '\tpublic static var COMMENT_WIDTHS:Array<Float> = %s;' % arr(c['widths']),
    '\tpublic static var COMMENT_RES:Array<Float> = %s;' % arr(c['res']),
    '\tpublic static var COMMENT_SMC_SCALE:Array<Float> = %s;' % arr(c['smcScale']),
    '\tpublic static inline var COMMENT_RED = 0x%06X;' % c['red'][0],
    '\tpublic static inline var COMMENT_RED_ALPHA = %r;' % float(c['red'][1]),
    '\tpublic static var COMMENT_KNOCK:Array<Float> = %s;' % arr(c['knock'][:3]),
    '\tpublic static inline var COMMENT_KNOCK_COLOR = 0x%06X;' % c['knock'][3],
    '\t// the score field (_field of sprite 6): its matrix [a, b, c, d, tx, ty], the text area and first baseline in the',
    '\t// field, the advances of "+0123456789" (anim "scoreGlyphs", pivot on the pen position), its glow',
    '\tpublic static var SCORE_FIELD:Array<Float> = %s;' % arr(c['field']),
    '\tpublic static inline var SCORE_X = %r;' % float(c['fieldX']),
    '\tpublic static inline var SCORE_W = %r;' % float(c['fieldW']),
    '\tpublic static inline var SCORE_BASE = %r;' % float(c['fieldBase']),
    '\tpublic static var SCORE_ADV:Array<Float> = %s;' % arr(c['adv']),
    '\tpublic static var SCORE_GLOW:Array<Float> = %s;' % arr(c['glow'][:3]),
    '\tpublic static inline var SCORE_GLOW_COLOR = 0x%06X;' % c['glow'][3],
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
assert c['knock'][4] == 1 and c['glow'][4] == 1, 'quality 1 glows only'
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
