"""Writes schizofuzz/Data.hx from the asset pipeline output (clips.json, meta.json).
usage: schizofuzz_data.py <out dir of schizofuzz_assets.py> <Data.hx>"""
import sys, json, os

OUT, DST = sys.argv[1], sys.argv[2]
clips = json.load(open(os.path.join(OUT, 'clips.json')))
meta = json.load(open(os.path.join(OUT, 'meta.json')))

js = json.dumps(clips, separators=(',', ':'))
assert '\\' not in js
js = js.replace('"', '\\"')


def arr(v):
    if isinstance(v, list):
        return '[' + ', '.join(arr(x) for x in v) + ']'
    return repr(float(v))


d = meta['digits']
lines = [
    'package schizofuzz;',
    '',
    '// generated by schizofuzz_data.py from the original SWF (do not edit)',
    'class Data {',
    '\tstatic var _clips:Dynamic = null;',
    '',
    '\t// timelines of the Flash symbols (see Clip)',
    '\tpublic static function clips():Dynamic {',
    '\t\tif (_clips == null)',
    '\t\t\t_clips = haxe.Json.parse(CLIPS);',
    '\t\treturn _clips;',
    '\t}',
    '',
    '\t// _height of bg_plan0..5',
    '\tpublic static var BG_HEIGHT:Array<Float> = %s;' % arr(meta['bgHeight']),
    '\t// _width of each frame of bgItem',
    '\tpublic static var BG_ITEM_WIDTH:Array<Float> = %s;' % arr(meta['bgItemWidth']),
    '\t// _width of startPlat for each frame of its sub (0: a frame the code never reaches)',
    '\tpublic static var PLATE_WIDTH:Array<Float> = %s;' % arr(meta['plateWidth']),
    '\t// bounds read by item.hitTest(x, y) (Flash: every shape rectangle through its full matrix), [xMin, xMax, yMin,',
    '\t// yMax] in the item: [frame - 1] with sub on its first frame, and the shield with sub on frame 2',
    '\tpublic static var ITEM_BOUNDS:Array<Array<Float>> = %s;' % arr(meta['itemBounds']),
    '\tpublic static var SHIELD_BOUNDS2:Array<Float> = %s;' % arr(meta['shieldBounds2']),
    '\t// arrow.txt (Impact 12, centred): glyphs "0123456789m" (anim "digits"), advances, text area and first baseline',
    '\tpublic static var DIGITS_ADV:Array<Float> = %s;' % arr(d['adv']),
    '\tpublic static inline var DIGITS_X = %r;' % float(d['x']),
    '\tpublic static inline var DIGITS_W = %r;' % float(d['w']),
    '\tpublic static inline var DIGITS_BASE = %r;' % float(d['base']),
    '\tpublic static inline var DIGITS_SY = %r;' % float(d['sy']),
    '',
    '\tstatic var CLIPS = "%s";' % js,
    '}',
    '',
]
open(DST, 'w', newline='\n').write('\n'.join(lines))
print('Data.hx %d bytes' % os.path.getsize(DST))
