package logico;

// generated by logico_data.py from the original SWF (do not edit)
class Data {
	// hit area of the ball buttons, per colour: radius of the union of its shapes (circles on the origin)
	public static var BALL_HIT:Array<Float> = [16.0, 16.0, 16.0, 15.8768, 15.8768, 15.8768, 15.8768];
	// pictures "ballCombo" per colour: one per value of tcoef below 1 in Game.updateCombo
	public static inline var COMBO_STEPS = 12;
	// frames of the partJunk timeline
	public static inline var JUNK_FRAMES = 14;
	// mcScore.field: glyphs (anims "glyph" and "glyphGlow", in this order), advances, right edge of the text
	// (right aligned) and baseline, in the coordinates of mcScore
	public static inline var SCORE_CHARS = "+0123456789x ";
	public static var SCORE_ADV:Array<Float> = [12.8203, 12.8906, 9.1641, 12.0703, 12.75, 12.0234, 12.9141, 13.0312, 9.4219, 12.8672, 13.0312, 10.4297, 4.2656];
	public static inline var SCORE_RIGHT = -3.0;
	public static inline var SCORE_BASE = -7.3891;
}
